// Nepal administrative divisions: Province → District → Municipality
// Source: Nepal Government, Ministry of Federal Affairs
// 7 Provinces, 77 Districts, key municipalities included

export interface Municipality {
  name_en: string;
  name_ne: string;
}

export interface District {
  name_en: string;
  name_ne: string;
  municipalities: Municipality[];
}

export interface Province {
  name_en: string;
  name_ne: string;
  districts: District[];
}

export const NEPAL_PROVINCES: Province[] = [
  {
    name_en: "Koshi Province",
    name_ne: "कोशी प्रदेश",
    districts: [
      {
        name_en: "Taplejung",
        name_ne: "ताप्लेजुङ",
        municipalities: [
          { name_en: "Phungling Municipality", name_ne: "फुङलिङ नगरपालिका" },
          { name_en: "Pathivara Yangwarak Rural Municipality", name_ne: "पाथीभरा याङवरक गाउँपालिका" },
          { name_en: "Sirijangha Rural Municipality", name_ne: "सिरीजङ्घा गाउँपालिका" },
          { name_en: "Aathrai Triveni Rural Municipality", name_ne: "आठराई त्रिवेणी गाउँपालिका" },
          { name_en: "Maiwakhola Rural Municipality", name_ne: "मैवाखोला गाउँपालिका" },
          { name_en: "Meringden Rural Municipality", name_ne: "मेरिङदेन गाउँपालिका" },
          { name_en: "Sidingba Rural Municipality", name_ne: "सिदिङ्बा गाउँपालिका" },
          { name_en: "Phaktanglung Rural Municipality", name_ne: "फक्ताङलुङ गाउँपालिका" },
          { name_en: "Mikwakhola Rural Municipality", name_ne: "मिक्वाखोला गाउँपालिका" },
        ],
      },
      {
        name_en: "Panchthar",
        name_ne: "पाँचथर",
        municipalities: [
          { name_en: "Phidim Municipality", name_ne: "फिदिम नगरपालिका" },
          { name_en: "Hilihang Rural Municipality", name_ne: "हिलिहाङ गाउँपालिका" },
          { name_en: "Kummayak Rural Municipality", name_ne: "कुम्मायक गाउँपालिका" },
          { name_en: "Miklajung Rural Municipality", name_ne: "मिक्लाजुङ गाउँपालिका" },
          { name_en: "Falgunanda Rural Municipality", name_ne: "फाल्गुनन्द गाउँपालिका" },
          { name_en: "Tumbewa Rural Municipality", name_ne: "तुम्बेवा गाउँपालिका" },
          { name_en: "Yangwarak Rural Municipality", name_ne: "याङवरक गाउँपालिका" },
          { name_en: "Phalelung Rural Municipality", name_ne: "फालेलुङ गाउँपालिका" },
        ],
      },
      {
        name_en: "Ilam",
        name_ne: "इलाम",
        municipalities: [
          { name_en: "Ilam Municipality", name_ne: "इलाम नगरपालिका" },
          { name_en: "Deumai Municipality", name_ne: "देउमाई नगरपालिका" },
          { name_en: "Mai Municipality", name_ne: "माई नगरपालिका" },
          { name_en: "Suryodaya Municipality", name_ne: "सूर्योदय नगरपालिका" },
          { name_en: "Phakphokthum Rural Municipality", name_ne: "फाकफोकथुम गाउँपालिका" },
          { name_en: "Mangsebung Rural Municipality", name_ne: "माङसेबुङ गाउँपालिका" },
          { name_en: "Chulachuli Rural Municipality", name_ne: "चुलाचुली गाउँपालिका" },
          { name_en: "Rong Rural Municipality", name_ne: "रोङ गाउँपालिका" },
          { name_en: "Sandakpur Rural Municipality", name_ne: "सन्दकपुर गाउँपालिका" },
          { name_en: "Mai Jogmai Rural Municipality", name_ne: "माईजोगमाई गाउँपालिका" },
        ],
      },
      {
        name_en: "Jhapa",
        name_ne: "झापा",
        municipalities: [
          { name_en: "Mechinagar Municipality", name_ne: "मेचीनगर नगरपालिका" },
          { name_en: "Bhadrapur Municipality", name_ne: "भद्रपुर नगरपालिका" },
          { name_en: "Birtamod Municipality", name_ne: "बिर्तामोड नगरपालिका" },
          { name_en: "Arjundhara Municipality", name_ne: "अर्जुनधारा नगरपालिका" },
          { name_en: "Kankai Municipality", name_ne: "कनकाई नगरपालिका" },
          { name_en: "Shivasatakshi Municipality", name_ne: "शिवसताक्षी नगरपालिका" },
          { name_en: "Gauradaha Municipality", name_ne: "गौरादह नगरपालिका" },
          { name_en: "Damak Municipality", name_ne: "दमक नगरपालिका" },
          { name_en: "Buddhashanti Rural Municipality", name_ne: "बुद्धशान्ति गाउँपालिका" },
          { name_en: "Haldibari Rural Municipality", name_ne: "हल्दीबारी गाउँपालिका" },
          { name_en: "Jhapa Rural Municipality", name_ne: "झापा गाउँपालिका" },
          { name_en: "Barhadashi Rural Municipality", name_ne: "बरहदशी गाउँपालिका" },
          { name_en: "Kamal Rural Municipality", name_ne: "कमल गाउँपालिका" },
          { name_en: "Kachankawal Rural Municipality", name_ne: "कचनकवल गाउँपालिका" },
          { name_en: "Gaurigunj Rural Municipality", name_ne: "गौरीगंज गाउँपालिका" },
        ],
      },
      {
        name_en: "Morang",
        name_ne: "मोरङ",
        municipalities: [
          { name_en: "Biratnagar Metropolitan City", name_ne: "विराटनगर महानगरपालिका" },
          { name_en: "Sundarharaicha Municipality", name_ne: "सुन्दरहरैंचा नगरपालिका" },
          { name_en: "Belbari Municipality", name_ne: "बेलबारी नगरपालिका" },
          { name_en: "Urlabari Municipality", name_ne: "उर्लाबारी नगरपालिका" },
          { name_en: "Pathari Shanishchare Municipality", name_ne: "पथरी शनिश्चरे नगरपालिका" },
          { name_en: "Rangeli Municipality", name_ne: "रंगेली नगरपालिका" },
          { name_en: "Letang Municipality", name_ne: "लेटाङ नगरपालिका" },
          { name_en: "Ratuwamai Municipality", name_ne: "रतुवामाई नगरपालिका" },
          { name_en: "Sunawarshi Municipality", name_ne: "सुनवर्षी नगरपालिका" },
          { name_en: "Jahada Rural Municipality", name_ne: "जहदा गाउँपालिका" },
          { name_en: "Katahari Rural Municipality", name_ne: "कटहरी गाउँपालिका" },
          { name_en: "Gramthan Rural Municipality", name_ne: "ग्रामथान गाउँपालिका" },
          { name_en: "Dhanpalthan Rural Municipality", name_ne: "धनपालथान गाउँपालिका" },
          { name_en: "Kerabari Rural Municipality", name_ne: "केराबारी गाउँपालिका" },
          { name_en: "Budhiganga Rural Municipality", name_ne: "बुढीगंगा गाउँपालिका" },
          { name_en: "Kanepokhari Rural Municipality", name_ne: "कानेपोखरी गाउँपालिका" },
          { name_en: "Miklajung Rural Municipality", name_ne: "मिक्लाजुङ गाउँपालिका" },
        ],
      },
      {
        name_en: "Sunsari",
        name_ne: "सुनसरी",
        municipalities: [
          { name_en: "Itahari Sub-Metropolitan City", name_ne: "इटहरी उपमहानगरपालिका" },
          { name_en: "Dharan Sub-Metropolitan City", name_ne: "धरान उपमहानगरपालिका" },
          { name_en: "Inaruwa Municipality", name_ne: "इनरुवा नगरपालिका" },
          { name_en: "Duhabi Municipality", name_ne: "दुहवी नगरपालिका" },
          { name_en: "Barahachhetra Municipality", name_ne: "बराहक्षेत्र नगरपालिका" },
          { name_en: "Ramdhuni Municipality", name_ne: "रामधुनी नगरपालिका" },
          { name_en: "Dewanganj Rural Municipality", name_ne: "देवानगंज गाउँपालिका" },
          { name_en: "Koshi Rural Municipality", name_ne: "कोशी गाउँपालिका" },
          { name_en: "Gadhi Rural Municipality", name_ne: "गढी गाउँपालिका" },
          { name_en: "Barju Rural Municipality", name_ne: "बर्जु गाउँपालिका" },
          { name_en: "Harinagara Rural Municipality", name_ne: "हरिनगरा गाउँपालिका" },
          { name_en: "Bhokraha Rural Municipality", name_ne: "भोक्राहा गाउँपालिका" },
        ],
      },
      {
        name_en: "Dhankuta",
        name_ne: "धनकुटा",
        municipalities: [
          { name_en: "Dhankuta Municipality", name_ne: "धनकुटा नगरपालिका" },
          { name_en: "Pakhribas Municipality", name_ne: "पाख्रिबास नगरपालिका" },
          { name_en: "Mahalaxmi Municipality", name_ne: "महालक्ष्मी नगरपालिका" },
          { name_en: "Sangurigadhi Rural Municipality", name_ne: "साँगुरीगढी गाउँपालिका" },
          { name_en: "Chhathar Jorpati Rural Municipality", name_ne: "छथर जोरपाटी गाउँपालिका" },
          { name_en: "Shahidbhumi Rural Municipality", name_ne: "शहीदभूमि गाउँपालिका" },
          { name_en: "Khalsa Chhintang Sahidbhumi Rural Municipality", name_ne: "खाल्सा छिन्ताङ साहिदभूमि गाउँपालिका" },
        ],
      },
      {
        name_en: "Terhathum",
        name_ne: "तेह्रथुम",
        municipalities: [
          { name_en: "Myanglung Municipality", name_ne: "म्याङलुङ नगरपालिका" },
          { name_en: "Laligurans Municipality", name_ne: "लालीगुराँस नगरपालिका" },
          { name_en: "Aathrai Rural Municipality", name_ne: "आठराई गाउँपालिका" },
          { name_en: "Chhathar Rural Municipality", name_ne: "छथर गाउँपालिका" },
          { name_en: "Phedap Rural Municipality", name_ne: "फेदाप गाउँपालिका" },
          { name_en: "Menchayam Rural Municipality", name_ne: "मेन्छयायेम गाउँपालिका" },
        ],
      },
      {
        name_en: "Sankhuwasabha",
        name_ne: "संखुवासभा",
        municipalities: [
          { name_en: "Khandbari Municipality", name_ne: "खाँदबारी नगरपालिका" },
          { name_en: "Chainpur Municipality", name_ne: "चैनपुर नगरपालिका" },
          { name_en: "Dharmadevi Municipality", name_ne: "धर्मदेवी नगरपालिका" },
          { name_en: "Madi Municipality", name_ne: "मादी नगरपालिका" },
          { name_en: "Panchakhapan Municipality", name_ne: "पाँचखपन नगरपालिका" },
          { name_en: "Makalu Rural Municipality", name_ne: "मकालु गाउँपालिका" },
          { name_en: "Chichila Rural Municipality", name_ne: "चिचिला गाउँपालिका" },
          { name_en: "Silichong Rural Municipality", name_ne: "सिलीचोङ गाउँपालिका" },
          { name_en: "Bhotkhola Rural Municipality", name_ne: "भोटखोला गाउँपालिका" },
          { name_en: "Sabhapokhari Rural Municipality", name_ne: "सभापोखरी गाउँपालिका" },
        ],
      },
      {
        name_en: "Bhojpur",
        name_ne: "भोजपुर",
        municipalities: [
          { name_en: "Bhojpur Municipality", name_ne: "भोजपुर नगरपालिका" },
          { name_en: "Shadanand Municipality", name_ne: "षडानन्द नगरपालिका" },
          { name_en: "Tyamke Maiyunm Rural Municipality", name_ne: "ट्याम्के मैयुम गाउँपालिका" },
          { name_en: "Arun Rural Municipality", name_ne: "अरुण गाउँपालिका" },
          { name_en: "Hatuwagadhi Rural Municipality", name_ne: "हतुवागढी गाउँपालिका" },
          { name_en: "Ramprasad Rai Rural Municipality", name_ne: "रामप्रसाद राई गाउँपालिका" },
          { name_en: "Aamchowk Rural Municipality", name_ne: "आमचोक गाउँपालिका" },
          { name_en: "Pauwadungma Rural Municipality", name_ne: "पौवादुङमा गाउँपालिका" },
          { name_en: "Salpasilichho Rural Municipality", name_ne: "साल्पासिलिछो गाउँपालिका" },
        ],
      },
      {
        name_en: "Solukhumbu",
        name_ne: "सोलुखुम्बु",
        municipalities: [
          { name_en: "Solududhkunda Municipality", name_ne: "सोलुदुधकुण्ड नगरपालिका" },
          { name_en: "Mapya Dudhkoshi Rural Municipality", name_ne: "माप्य दुधकोशी गाउँपालिका" },
          { name_en: "Khumbu Pasanglhamu Rural Municipality", name_ne: "खुम्बु पासाङल्हामु गाउँपालिका" },
          { name_en: "Likhu Pike Rural Municipality", name_ne: "लिखु पिके गाउँपालिका" },
          { name_en: "Necha Salyan Rural Municipality", name_ne: "नेचासल्यान गाउँपालिका" },
          { name_en: "Thulung Dudhkoshi Rural Municipality", name_ne: "थुलुङ दुधकोशी गाउँपालिका" },
          { name_en: "Sotang Rural Municipality", name_ne: "सोताङ गाउँपालिका" },
        ],
      },
      {
        name_en: "Okhaldhunga",
        name_ne: "ओखलढुङ्गा",
        municipalities: [
          { name_en: "Siddhicharan Municipality", name_ne: "सिद्धिचरण नगरपालिका" },
          { name_en: "Manebhanjyang Rural Municipality", name_ne: "मानेभञ्ज्याङ गाउँपालिका" },
          { name_en: "Champadevi Rural Municipality", name_ne: "चम्पादेवी गाउँपालिका" },
          { name_en: "Sunkoshi Rural Municipality", name_ne: "सुनकोशी गाउँपालिका" },
          { name_en: "Likhu Rural Municipality", name_ne: "लिखु गाउँपालिका" },
          { name_en: "Chisankhugadhi Rural Municipality", name_ne: "चिसंखुगढी गाउँपालिका" },
          { name_en: "Molung Rural Municipality", name_ne: "मोलुङ गाउँपालिका" },
          { name_en: "Khijidemba Rural Municipality", name_ne: "खिजिदेम्बा गाउँपालिका" },
        ],
      },
      {
        name_en: "Khotang",
        name_ne: "खोटाङ",
        municipalities: [
          { name_en: "Diktel Rupakot Majhuwagadhi Municipality", name_ne: "दिक्तेल रुपाकोट मझुवागढी नगरपालिका" },
          { name_en: "Halesi Tuwachung Municipality", name_ne: "हलेसी तुवाचुङ नगरपालिका" },
          { name_en: "Khotehang Rural Municipality", name_ne: "खोटेहाङ गाउँपालिका" },
          { name_en: "Diprung Chuichumma Rural Municipality", name_ne: "दिप्रुङ चुइचुम्मा गाउँपालिका" },
          { name_en: "Ainselukhark Rural Municipality", name_ne: "ऐँसेलुखर्क गाउँपालिका" },
          { name_en: "Rawa Besi Rural Municipality", name_ne: "रावा बेसी गाउँपालिका" },
          { name_en: "Sakela Rural Municipality", name_ne: "साकेला गाउँपालिका" },
          { name_en: "Barahapokhari Rural Municipality", name_ne: "बराहपोखरी गाउँपालिका" },
          { name_en: "Jantedhunga Rural Municipality", name_ne: "जन्तेढुङ्गा गाउँपालिका" },
          { name_en: "Kepilasgadhi Rural Municipality", name_ne: "केपिलासगढी गाउँपालिका" },
        ],
      },
      {
        name_en: "Udayapur",
        name_ne: "उदयपुर",
        municipalities: [
          { name_en: "Triyuga Municipality", name_ne: "त्रियुगा नगरपालिका" },
          { name_en: "Katari Municipality", name_ne: "कटारी नगरपालिका" },
          { name_en: "Chaudandigadhi Municipality", name_ne: "चौदण्डीगढी नगरपालिका" },
          { name_en: "Belaka Municipality", name_ne: "बेलका नगरपालिका" },
          { name_en: "Udayapurgadhi Rural Municipality", name_ne: "उदयपुरगढी गाउँपालिका" },
          { name_en: "Rautamai Rural Municipality", name_ne: "रौतामाई गाउँपालिका" },
          { name_en: "Tapli Rural Municipality", name_ne: "ताप्ली गाउँपालिका" },
          { name_en: "Limchungbung Rural Municipality", name_ne: "लिम्चुङबुङ गाउँपालिका" },
        ],
      },
    ],
  },
  {
    name_en: "Madhesh Province",
    name_ne: "मधेश प्रदेश",
    districts: [
      {
        name_en: "Saptari",
        name_ne: "सप्तरी",
        municipalities: [
          { name_en: "Rajbiraj Municipality", name_ne: "राजविराज नगरपालिका" },
          { name_en: "Kanchanrup Municipality", name_ne: "कञ्चनरुप नगरपालिका" },
          { name_en: "Dakneshwori Municipality", name_ne: "डाक्नेश्वरी नगरपालिका" },
          { name_en: "Bodebarsain Municipality", name_ne: "बोदेबरसाइन नगरपालिका" },
          { name_en: "Shambhunath Municipality", name_ne: "शम्भुनाथ नगरपालिका" },
          { name_en: "Hanumannagar Kankalini Municipality", name_ne: "हनुमाननगर कङ्कालिनी नगरपालिका" },
          { name_en: "Surunga Municipality", name_ne: "सुरुंगा नगरपालिका" },
          { name_en: "Saptakoshi Municipality", name_ne: "सप्तकोशी नगरपालिका" },
          { name_en: "Chhinnamasta Rural Municipality", name_ne: "छिन्नमस्ता गाउँपालिका" },
          { name_en: "Tilathi Koiladi Rural Municipality", name_ne: "तिलाठी कोइलाडी गाउँपालिका" },
          { name_en: "Agnisair Krishna Savaran Rural Municipality", name_ne: "अग्निसाइर कृष्णसवरन गाउँपालिका" },
          { name_en: "Rupani Rural Municipality", name_ne: "रूपनी गाउँपालिका" },
          { name_en: "Tirhut Rural Municipality", name_ne: "तिरहुत गाउँपालिका" },
          { name_en: "Mahadeva Rural Municipality", name_ne: "महादेवा गाउँपालिका" },
          { name_en: "Bishnupur Rural Municipality", name_ne: "विष्णुपुर गाउँपालिका" },
          { name_en: "Rajgadh Rural Municipality", name_ne: "राजगढ गाउँपालिका" },
          { name_en: "Balan-Bihul Rural Municipality", name_ne: "बलान-बिहुल गाउँपालिका" },
        ],
      },
      {
        name_en: "Siraha",
        name_ne: "सिराहा",
        municipalities: [
          { name_en: "Siraha Municipality", name_ne: "सिराहा नगरपालिका" },
          { name_en: "Lahan Municipality", name_ne: "लहान नगरपालिका" },
          { name_en: "Dhangadhimai Municipality", name_ne: "धनगढीमाई नगरपालिका" },
          { name_en: "Mirchaiya Municipality", name_ne: "मिर्चैया नगरपालिका" },
          { name_en: "Golbazar Municipality", name_ne: "गोलबजार नगरपालिका" },
          { name_en: "Kalyanpur Municipality", name_ne: "कल्याणपुर नगरपालिका" },
          { name_en: "Sukhipur Municipality", name_ne: "सुखीपुर नगरपालिका" },
          { name_en: "Karjanha Municipality", name_ne: "कर्जन्हा नगरपालिका" },
        ],
      },
      {
        name_en: "Dhanusha",
        name_ne: "धनुषा",
        municipalities: [
          { name_en: "Janakpur Sub-Metropolitan City", name_ne: "जनकपुरधाम उपमहानगरपालिका" },
          { name_en: "Chhireshwornath Municipality", name_ne: "क्षिरेश्वरनाथ नगरपालिका" },
          { name_en: "Ganeshman Charnath Municipality", name_ne: "गणेशमान चारनाथ नगरपालिका" },
          { name_en: "Dhanusadham Municipality", name_ne: "धनुषाधाम नगरपालिका" },
          { name_en: "Nagarain Municipality", name_ne: "नगराइन नगरपालिका" },
          { name_en: "Bideha Municipality", name_ne: "विदेह नगरपालिका" },
          { name_en: "Mithila Municipality", name_ne: "मिथिला नगरपालिका" },
          { name_en: "Shahidnagar Municipality", name_ne: "शहीदनगर नगरपालिका" },
          { name_en: "Sabaila Municipality", name_ne: "सबैला नगरपालिका" },
          { name_en: "Hansapur Municipality", name_ne: "हंसपुर नगरपालिका" },
          { name_en: "Kamala Municipality", name_ne: "कमला नगरपालिका" },
          { name_en: "Mithila Bihari Municipality", name_ne: "मिथिला बिहारी नगरपालिका" },
          { name_en: "Bateshwar Rural Municipality", name_ne: "बटेश्वर गाउँपालिका" },
          { name_en: "Janak Nandini Rural Municipality", name_ne: "जनकनन्दिनी गाउँपालिका" },
          { name_en: "Lakshminya Rural Municipality", name_ne: "लक्ष्मीनिया गाउँपालिका" },
          { name_en: "Aaurahi Rural Municipality", name_ne: "औरही गाउँपालिका" },
          { name_en: "Dhanauji Rural Municipality", name_ne: "धनौजी गाउँपालिका" },
          { name_en: "Mukhiyapatti Musaharmiya Rural Municipality", name_ne: "मुखियापट्टी मुसहरमिया गाउँपालिका" },
        ],
      },
      {
        name_en: "Mahottari",
        name_ne: "महोत्तरी",
        municipalities: [
          { name_en: "Jaleshwor Municipality", name_ne: "जलेश्वर नगरपालिका" },
          { name_en: "Bardibas Municipality", name_ne: "बर्दिबास नगरपालिका" },
          { name_en: "Gaushala Municipality", name_ne: "गौशाला नगरपालिका" },
          { name_en: "Loharpatti Municipality", name_ne: "लोहरपट्टी नगरपालिका" },
          { name_en: "Ramgopalpur Municipality", name_ne: "रामगोपालपुर नगरपालिका" },
          { name_en: "Aurahi Municipality", name_ne: "औरही नगरपालिका" },
          { name_en: "Balawa Municipality", name_ne: "बलवा नगरपालिका" },
          { name_en: "Manara Siswa Municipality", name_ne: "मनरा शिसवा नगरपालिका" },
          { name_en: "Matihani Municipality", name_ne: "मटिहानी नगरपालिका" },
          { name_en: "Bhangaha Municipality", name_ne: "भँगाहा नगरपालिका" },
        ],
      },
      {
        name_en: "Sarlahi",
        name_ne: "सर्लाही",
        municipalities: [
          { name_en: "Malangwa Municipality", name_ne: "मलंगवा नगरपालिका" },
          { name_en: "Ishworpur Municipality", name_ne: "ईश्वरपुर नगरपालिका" },
          { name_en: "Lalbandi Municipality", name_ne: "लालबन्दी नगरपालिका" },
          { name_en: "Haripur Municipality", name_ne: "हरिपुर नगरपालिका" },
          { name_en: "Barahathawa Municipality", name_ne: "बरहथवा नगरपालिका" },
          { name_en: "Godaita Municipality", name_ne: "गोडैता नगरपालिका" },
          { name_en: "Hariwan Municipality", name_ne: "हरिवन नगरपालिका" },
          { name_en: "Bagmati Municipality", name_ne: "बागमती नगरपालिका" },
          { name_en: "Balara Municipality", name_ne: "बलरा नगरपालिका" },
          { name_en: "Kabilasi Municipality", name_ne: "कविलासी नगरपालिका" },
        ],
      },
      {
        name_en: "Rautahat",
        name_ne: "रौतहट",
        municipalities: [
          { name_en: "Gaur Municipality", name_ne: "गौर नगरपालिका" },
          { name_en: "Garuda Municipality", name_ne: "गरुडा नगरपालिका" },
          { name_en: "Chandrapur Municipality", name_ne: "चन्द्रपुर नगरपालिका" },
          { name_en: "Brindaban Municipality", name_ne: "वृन्दावन नगरपालिका" },
          { name_en: "Gujara Municipality", name_ne: "गुजरा नगरपालिका" },
          { name_en: "Baudhimai Municipality", name_ne: "बौधीमाई नगरपालिका" },
          { name_en: "Ishanath Municipality", name_ne: "ईशनाथ नगरपालिका" },
          { name_en: "Madhav Narayan Municipality", name_ne: "माधव नारायण नगरपालिका" },
          { name_en: "Maulapur Municipality", name_ne: "मौलापुर नगरपालिका" },
          { name_en: "Paroha Municipality", name_ne: "परोहा नगरपालिका" },
          { name_en: "Phatuwa Bijayapur Municipality", name_ne: "फतुवाबिजयपुर नगरपालिका" },
          { name_en: "Dewahi Gonahi Municipality", name_ne: "देवाही गोनाही नगरपालिका" },
          { name_en: "Rajpur Municipality", name_ne: "राजपुर नगरपालिका" },
        ],
      },
      {
        name_en: "Bara",
        name_ne: "बारा",
        municipalities: [
          { name_en: "Kalaiya Sub-Metropolitan City", name_ne: "कलैया उपमहानगरपालिका" },
          { name_en: "Jeetpur Simara Sub-Metropolitan City", name_ne: "जीतपुर सिमरा उपमहानगरपालिका" },
          { name_en: "Kolhabi Municipality", name_ne: "कोल्हवी नगरपालिका" },
          { name_en: "Nijgadh Municipality", name_ne: "निजगढ नगरपालिका" },
          { name_en: "Mahagadhimai Municipality", name_ne: "महागढीमाई नगरपालिका" },
          { name_en: "Simraungadh Municipality", name_ne: "सिम्रौनगढ नगरपालिका" },
          { name_en: "Pacharauta Municipality", name_ne: "पचरौता नगरपालिका" },
          { name_en: "Pheta Rural Municipality", name_ne: "फेटा गाउँपालिका" },
          { name_en: "Devtal Rural Municipality", name_ne: "देवताल गाउँपालिका" },
          { name_en: "Prasauni Rural Municipality", name_ne: "प्रसौनी गाउँपालिका" },
          { name_en: "Suwarna Rural Municipality", name_ne: "सुवर्ण गाउँपालिका" },
          { name_en: "Baragadhi Rural Municipality", name_ne: "बारागढी गाउँपालिका" },
          { name_en: "Karaiyamai Rural Municipality", name_ne: "करैयामाई गाउँपालिका" },
          { name_en: "Parwanipur Rural Municipality", name_ne: "परवानीपुर गाउँपालिका" },
          { name_en: "Bishrampur Rural Municipality", name_ne: "विश्रामपुर गाउँपालिका" },
          { name_en: "Adarsh Kotwal Rural Municipality", name_ne: "आदर्श कोटवाल गाउँपालिका" },
        ],
      },
      {
        name_en: "Parsa",
        name_ne: "पर्सा",
        municipalities: [
          { name_en: "Birgunj Metropolitan City", name_ne: "वीरगञ्ज महानगरपालिका" },
          { name_en: "Pokhariya Municipality", name_ne: "पोखरिया नगरपालिका" },
          { name_en: "Bahudarmai Municipality", name_ne: "बहुदरमाई नगरपालिका" },
          { name_en: "Parsagadhi Municipality", name_ne: "पर्सागढी नगरपालिका" },
          { name_en: "Bindabasini Rural Municipality", name_ne: "विन्दबासिनी गाउँपालिका" },
          { name_en: "Chhipaharmai Rural Municipality", name_ne: "छिपहरमाई गाउँपालिका" },
          { name_en: "Dhobini Rural Municipality", name_ne: "ढोबिनी गाउँपालिका" },
          { name_en: "Jagarnathpur Rural Municipality", name_ne: "जगरनाथपुर गाउँपालिका" },
          { name_en: "Jirabhawani Rural Municipality", name_ne: "जीराभवानी गाउँपालिका" },
          { name_en: "Kalikamai Rural Municipality", name_ne: "कालिकामाई गाउँपालिका" },
          { name_en: "Pakaha Mainpur Rural Municipality", name_ne: "पकाहा मैनपुर गाउँपालिका" },
          { name_en: "Paterwa Sugauli Rural Municipality", name_ne: "पटेर्वा सुगौली गाउँपालिका" },
          { name_en: "Sakhuwa Prasauni Rural Municipality", name_ne: "सखुवा प्रसौनी गाउँपालिका" },
          { name_en: "Thori Rural Municipality", name_ne: "ठोरी गाउँपालिका" },
        ],
      },
    ],
  },
  {
    name_en: "Bagmati Province",
    name_ne: "बागमती प्रदेश",
    districts: [
      {
        name_en: "Dolakha",
        name_ne: "दोलखा",
        municipalities: [
          { name_en: "Bhimeshwor Municipality", name_ne: "भीमेश्वर नगरपालिका" },
          { name_en: "Jiri Municipality", name_ne: "जिरी नगरपालिका" },
          { name_en: "Kalinchok Rural Municipality", name_ne: "कालिन्चोक गाउँपालिका" },
          { name_en: "Melung Rural Municipality", name_ne: "मेलुङ गाउँपालिका" },
          { name_en: "Bigu Rural Municipality", name_ne: "बिगु गाउँपालिका" },
          { name_en: "Gaurishankar Rural Municipality", name_ne: "गौरीशंकर गाउँपालिका" },
          { name_en: "Baiteshwor Rural Municipality", name_ne: "बैतेश्वर गाउँपालिका" },
          { name_en: "Sailung Rural Municipality", name_ne: "सैलुङ गाउँपालिका" },
          { name_en: "Tamakoshi Rural Municipality", name_ne: "तामाकोशी गाउँपालिका" },
        ],
      },
      {
        name_en: "Sindhupalchok",
        name_ne: "सिन्धुपाल्चोक",
        municipalities: [
          { name_en: "Chautara Sangachokgadhi Municipality", name_ne: "चौतारा साँगाचोकगढी नगरपालिका" },
          { name_en: "Melamchi Municipality", name_ne: "मेलम्ची नगरपालिका" },
          { name_en: "Bahrabise Municipality", name_ne: "बाह्रबिसे नगरपालिका" },
          { name_en: "Helambu Rural Municipality", name_ne: "हेलम्बु गाउँपालिका" },
          { name_en: "Balefi Rural Municipality", name_ne: "बलेफी गाउँपालिका" },
          { name_en: "Sunkoshi Rural Municipality", name_ne: "सुनकोशी गाउँपालिका" },
          { name_en: "Indrawati Rural Municipality", name_ne: "इन्द्रावती गाउँपालिका" },
          { name_en: "Jugal Rural Municipality", name_ne: "जुगल गाउँपालिका" },
          { name_en: "Panchpokhari Thangpal Rural Municipality", name_ne: "पाँचपोखरी थाङपाल गाउँपालिका" },
          { name_en: "Lisankhu Pakhar Rural Municipality", name_ne: "लिसंखु पाखर गाउँपालिका" },
          { name_en: "Tripurasundari Rural Municipality", name_ne: "त्रिपुरासुन्दरी गाउँपालिका" },
          { name_en: "Bhotekoshi Rural Municipality", name_ne: "भोटेकोशी गाउँपालिका" },
        ],
      },
      {
        name_en: "Rasuwa",
        name_ne: "रसुवा",
        municipalities: [
          { name_en: "Uttargaya Rural Municipality", name_ne: "उत्तरगया गाउँपालिका" },
          { name_en: "Kalika Rural Municipality", name_ne: "कालिका गाउँपालिका" },
          { name_en: "Naukunda Rural Municipality", name_ne: "नौकुण्ड गाउँपालिका" },
          { name_en: "Parvati Kunda Rural Municipality", name_ne: "पार्वतीकुण्ड गाउँपालिका" },
          { name_en: "Ama Chhodingmo Rural Municipality", name_ne: "आमाछोदिङमो गाउँपालिका" },
          { name_en: "Gosaikunda Rural Municipality", name_ne: "गोसाईकुण्ड गाउँपालिका" },
        ],
      },
      {
        name_en: "Dhading",
        name_ne: "धादिङ",
        municipalities: [
          { name_en: "Dhunibeshi Municipality", name_ne: "धुनीबेशी नगरपालिका" },
          { name_en: "Nilkantha Municipality", name_ne: "नीलकण्ठ नगरपालिका" },
          { name_en: "Benighat Rorang Rural Municipality", name_ne: "बेनीघाट रोराङ गाउँपालिका" },
          { name_en: "Gajuri Rural Municipality", name_ne: "गजुरी गाउँपालिका" },
          { name_en: "Galchhi Rural Municipality", name_ne: "गल्छी गाउँपालिका" },
          { name_en: "Gangajamuna Rural Municipality", name_ne: "गंगाजमुना गाउँपालिका" },
          { name_en: "Jwalamukhi Rural Municipality", name_ne: "ज्वालामुखी गाउँपालिका" },
          { name_en: "Khaniyabas Rural Municipality", name_ne: "खनियाबास गाउँपालिका" },
          { name_en: "Netrawati Dabjong Rural Municipality", name_ne: "नेत्रावती डबजोङ गाउँपालिका" },
          { name_en: "Rubi Valley Rural Municipality", name_ne: "रुवी भ्याली गाउँपालिका" },
          { name_en: "Siddhalek Rural Municipality", name_ne: "सिद्धलेक गाउँपालिका" },
          { name_en: "Thakre Rural Municipality", name_ne: "थाक्रे गाउँपालिका" },
          { name_en: "Tripurasundari Rural Municipality", name_ne: "त्रिपुरासुन्दरी गाउँपालिका" },
        ],
      },
      {
        name_en: "Nuwakot",
        name_ne: "नुवाकोट",
        municipalities: [
          { name_en: "Bidur Municipality", name_ne: "बिदुर नगरपालिका" },
          { name_en: "Belkotgadhi Municipality", name_ne: "बेलकोटगढी नगरपालिका" },
          { name_en: "Dupcheshwar Rural Municipality", name_ne: "दुप्चेश्वर गाउँपालिका" },
          { name_en: "Kakani Rural Municipality", name_ne: "ककनी गाउँपालिका" },
          { name_en: "Kispang Rural Municipality", name_ne: "किस्पाङ गाउँपालिका" },
          { name_en: "Likhu Rural Municipality", name_ne: "लिखु गाउँपालिका" },
          { name_en: "Meghang Rural Municipality", name_ne: "म्यगाङ गाउँपालिका" },
          { name_en: "Panchakanya Rural Municipality", name_ne: "पञ्चकन्या गाउँपालिका" },
          { name_en: "Shivapuri Rural Municipality", name_ne: "शिवपुरी गाउँपालिका" },
          { name_en: "Suryagadhi Rural Municipality", name_ne: "सूर्यगढी गाउँपालिका" },
          { name_en: "Tadi Rural Municipality", name_ne: "तादी गाउँपालिका" },
          { name_en: "Tarkeshwar Rural Municipality", name_ne: "तारकेश्वर गाउँपालिका" },
        ],
      },
      {
        name_en: "Kathmandu",
        name_ne: "काठमाडौं",
        municipalities: [
          { name_en: "Kathmandu Metropolitan City", name_ne: "काठमाडौं महानगरपालिका" },
          { name_en: "Kirtipur Municipality", name_ne: "कीर्तिपुर नगरपालिका" },
          { name_en: "Kageshwori Manohara Municipality", name_ne: "कागेश्वरी मनोहरा नगरपालिका" },
          { name_en: "Gokarneshwor Municipality", name_ne: "गोकर्णेश्वर नगरपालिका" },
          { name_en: "Chandragiri Municipality", name_ne: "चन्द्रागिरी नगरपालिका" },
          { name_en: "Tokha Municipality", name_ne: "टोखा नगरपालिका" },
          { name_en: "Tarkeshwor Municipality", name_ne: "तारकेश्वर नगरपालिका" },
          { name_en: "Nagarjun Municipality", name_ne: "नागार्जुन नगरपालिका" },
          { name_en: "Budhanilkantha Municipality", name_ne: "बूढानीलकण्ठ नगरपालिका" },
          { name_en: "Dakshinkali Municipality", name_ne: "दक्षिणकाली नगरपालिका" },
          { name_en: "Shankharapur Municipality", name_ne: "शंखरापुर नगरपालिका" },
        ],
      },
      {
        name_en: "Bhaktapur",
        name_ne: "भक्तपुर",
        municipalities: [
          { name_en: "Bhaktapur Municipality", name_ne: "भक्तपुर नगरपालिका" },
          { name_en: "Madhyapur Thimi Municipality", name_ne: "मध्यपुर थिमी नगरपालिका" },
          { name_en: "Suryabinayak Municipality", name_ne: "सूर्यबिनायक नगरपालिका" },
          { name_en: "Changunarayan Municipality", name_ne: "चाँगुनारायण नगरपालिका" },
        ],
      },
      {
        name_en: "Lalitpur",
        name_ne: "ललितपुर",
        municipalities: [
          { name_en: "Lalitpur Metropolitan City", name_ne: "ललितपुर महानगरपालिका" },
          { name_en: "Godawari Municipality", name_ne: "गोदावरी नगरपालिका" },
          { name_en: "Mahalaxmi Municipality", name_ne: "महालक्ष्मी नगरपालिका" },
          { name_en: "Konjyosom Rural Municipality", name_ne: "कोन्ज्योसोम गाउँपालिका" },
          { name_en: "Bagmati Rural Municipality", name_ne: "बागमती गाउँपालिका" },
          { name_en: "Mahankal Rural Municipality", name_ne: "महाङ्काल गाउँपालिका" },
        ],
      },
      {
        name_en: "Kavrepalanchok",
        name_ne: "काभ्रेपलाञ्चोक",
        municipalities: [
          { name_en: "Dhulikhel Municipality", name_ne: "धुलिखेल नगरपालिका" },
          { name_en: "Banepa Municipality", name_ne: "बनेपा नगरपालिका" },
          { name_en: "Panauti Municipality", name_ne: "पनौती नगरपालिका" },
          { name_en: "Panchkhal Municipality", name_ne: "पाँचखाल नगरपालिका" },
          { name_en: "Namobuddha Municipality", name_ne: "नमोबुद्ध नगरपालिका" },
          { name_en: "Mandandeupur Municipality", name_ne: "मण्डनदेउपुर नगरपालिका" },
          { name_en: "Bethanchowk Rural Municipality", name_ne: "बेथानचोक गाउँपालिका" },
          { name_en: "Bhumlu Rural Municipality", name_ne: "भुम्लु गाउँपालिका" },
          { name_en: "Chaurideurali Rural Municipality", name_ne: "चौरीदेउराली गाउँपालिका" },
          { name_en: "Khanikhola Rural Municipality", name_ne: "खानीखोला गाउँपालिका" },
          { name_en: "Mahabharat Rural Municipality", name_ne: "महाभारत गाउँपालिका" },
          { name_en: "Roshi Rural Municipality", name_ne: "रोशी गाउँपालिका" },
          { name_en: "Temal Rural Municipality", name_ne: "तेमाल गाउँपालिका" },
        ],
      },
      {
        name_en: "Ramechhap",
        name_ne: "रामेछाप",
        municipalities: [
          { name_en: "Manthali Municipality", name_ne: "मन्थली नगरपालिका" },
          { name_en: "Ramechhap Municipality", name_ne: "रामेछाप नगरपालिका" },
          { name_en: "Doramba Rural Municipality", name_ne: "दोरम्बा गाउँपालिका" },
          { name_en: "Gokulganga Rural Municipality", name_ne: "गोकुलगंगा गाउँपालिका" },
          { name_en: "Khandadevi Rural Municipality", name_ne: "खाँडादेवी गाउँपालिका" },
          { name_en: "Likhu Tamakoshi Rural Municipality", name_ne: "लिखु तामाकोशी गाउँपालिका" },
          { name_en: "Sunapati Rural Municipality", name_ne: "सुनापती गाउँपालिका" },
          { name_en: "Umakunda Rural Municipality", name_ne: "उमाकुण्ड गाउँपालिका" },
        ],
      },
      {
        name_en: "Sindhuli",
        name_ne: "सिन्धुली",
        municipalities: [
          { name_en: "Kamalamai Municipality", name_ne: "कमलामाई नगरपालिका" },
          { name_en: "Dudhauli Municipality", name_ne: "दुधौली नगरपालिका" },
          { name_en: "Golanjor Rural Municipality", name_ne: "गोलन्जोर गाउँपालिका" },
          { name_en: "Ghyanglekh Rural Municipality", name_ne: "घ्याङलेख गाउँपालिका" },
          { name_en: "Hariharpurgadhi Rural Municipality", name_ne: "हरिहरपुरगढी गाउँपालिका" },
          { name_en: "Marin Rural Municipality", name_ne: "मरिण गाउँपालिका" },
          { name_en: "Phikkal Rural Municipality", name_ne: "फिक्कल गाउँपालिका" },
          { name_en: "Sunkoshi Rural Municipality", name_ne: "सुनकोशी गाउँपालिका" },
          { name_en: "Tinpatan Rural Municipality", name_ne: "तीनपाटन गाउँपालिका" },
        ],
      },
      {
        name_en: "Makwanpur",
        name_ne: "मकवानपुर",
        municipalities: [
          { name_en: "Hetauda Sub-Metropolitan City", name_ne: "हेटौँडा उपमहानगरपालिका" },
          { name_en: "Thaha Municipality", name_ne: "थाहा नगरपालिका" },
          { name_en: "Bhimphedi Rural Municipality", name_ne: "भीमफेदी गाउँपालिका" },
          { name_en: "Bagmati Rural Municipality", name_ne: "बागमती गाउँपालिका" },
          { name_en: "Bakaiya Rural Municipality", name_ne: "बकैया गाउँपालिका" },
          { name_en: "Indrasarowar Rural Municipality", name_ne: "इन्द्रसरोवर गाउँपालिका" },
          { name_en: "Kailash Rural Municipality", name_ne: "कैलाश गाउँपालिका" },
          { name_en: "Makawanpurgadhi Rural Municipality", name_ne: "मकवानपुरगढी गाउँपालिका" },
          { name_en: "Manahari Rural Municipality", name_ne: "मनहरी गाउँपालिका" },
          { name_en: "Raksirang Rural Municipality", name_ne: "राक्सिराङ गाउँपालिका" },
        ],
      },
      {
        name_en: "Chitwan",
        name_ne: "चितवन",
        municipalities: [
          { name_en: "Bharatpur Metropolitan City", name_ne: "भरतपुर महानगरपालिका" },
          { name_en: "Ratnanagar Municipality", name_ne: "रत्ननगर नगरपालिका" },
          { name_en: "Khairahani Municipality", name_ne: "खैरहनी नगरपालिका" },
          { name_en: "Kalika Municipality", name_ne: "कालिका नगरपालिका" },
          { name_en: "Rapti Municipality", name_ne: "राप्ती नगरपालिका" },
          { name_en: "Madi Municipality", name_ne: "माडी नगरपालिका" },
          { name_en: "Ichchhakamana Rural Municipality", name_ne: "इच्छाकामना गाउँपालिका" },
        ],
      },
    ],
  },
  {
    name_en: "Gandaki Province",
    name_ne: "गण्डकी प्रदेश",
    districts: [
      {
        name_en: "Gorkha",
        name_ne: "गोरखा",
        municipalities: [
          { name_en: "Gorkha Municipality", name_ne: "गोरखा नगरपालिका" },
          { name_en: "Palungtar Municipality", name_ne: "पालुंगटार नगरपालिका" },
          { name_en: "Sulikot Rural Municipality", name_ne: "सुलीकोट गाउँपालिका" },
          { name_en: "Siranchowk Rural Municipality", name_ne: "सिरानचोक गाउँपालिका" },
          { name_en: "Ajirkot Rural Municipality", name_ne: "अजिरकोट गाउँपालिका" },
          { name_en: "Aarughat Rural Municipality", name_ne: "आरुघाट गाउँपालिका" },
          { name_en: "Barpak Sulikot Rural Municipality", name_ne: "बारपाक सुलीकोट गाउँपालिका" },
          { name_en: "Bhimsen Rural Municipality", name_ne: "भीमसेन गाउँपालिका" },
          { name_en: "Chum Nubri Rural Municipality", name_ne: "चुम नुब्री गाउँपालिका" },
          { name_en: "Dharche Rural Municipality", name_ne: "धार्चे गाउँपालिका" },
          { name_en: "Shahid Lakhan Rural Municipality", name_ne: "शहीद लखन गाउँपालिका" },
        ],
      },
      {
        name_en: "Lamjung",
        name_ne: "लमजुङ",
        municipalities: [
          { name_en: "Besishahar Municipality", name_ne: "बेसीशहर नगरपालिका" },
          { name_en: "Madhya Nepal Municipality", name_ne: "मध्यनेपाल नगरपालिका" },
          { name_en: "Rainas Municipality", name_ne: "राइनास नगरपालिका" },
          { name_en: "Sundarbazar Municipality", name_ne: "सुन्दरबजार नगरपालिका" },
          { name_en: "Dordi Rural Municipality", name_ne: "दोर्दी गाउँपालिका" },
          { name_en: "Dudhpokhari Rural Municipality", name_ne: "दूधपोखरी गाउँपालिका" },
          { name_en: "Kwholasothar Rural Municipality", name_ne: "क्व्होलासोथार गाउँपालिका" },
          { name_en: "Marsyangdi Rural Municipality", name_ne: "मर्स्याङदी गाउँपालिका" },
        ],
      },
      {
        name_en: "Tanahu",
        name_ne: "तनहुँ",
        municipalities: [
          { name_en: "Bhanu Municipality", name_ne: "भानु नगरपालिका" },
          { name_en: "Byas Municipality", name_ne: "व्यास नगरपालिका" },
          { name_en: "Shuklagandaki Municipality", name_ne: "शुक्लागण्डकी नगरपालिका" },
          { name_en: "Bhimad Municipality", name_ne: "भिमाद नगरपालिका" },
          { name_en: "Anbukhaireni Rural Municipality", name_ne: "आँबुखैरेनी गाउँपालिका" },
          { name_en: "Bandipur Rural Municipality", name_ne: "बन्दीपुर गाउँपालिका" },
          { name_en: "Devghat Rural Municipality", name_ne: "देवघाट गाउँपालिका" },
          { name_en: "Ghiring Rural Municipality", name_ne: "घिरिङ गाउँपालिका" },
          { name_en: "Myagde Rural Municipality", name_ne: "म्याग्दे गाउँपालिका" },
          { name_en: "Rishing Rural Municipality", name_ne: "ऋषिङ गाउँपालिका" },
        ],
      },
      {
        name_en: "Syangja",
        name_ne: "स्याङजा",
        municipalities: [
          { name_en: "Putalibazar Municipality", name_ne: "पुतलीबजार नगरपालिका" },
          { name_en: "Bhirkot Municipality", name_ne: "भीरकोट नगरपालिका" },
          { name_en: "Galyang Municipality", name_ne: "गल्याङ नगरपालिका" },
          { name_en: "Chapakot Municipality", name_ne: "चापाकोट नगरपालिका" },
          { name_en: "Waling Municipality", name_ne: "वालिङ नगरपालिका" },
          { name_en: "Arjun Chaupari Rural Municipality", name_ne: "अर्जुन चौपारी गाउँपालिका" },
          { name_en: "Aandhikhola Rural Municipality", name_ne: "आँधीखोला गाउँपालिका" },
          { name_en: "Biruwa Rural Municipality", name_ne: "बिरुवा गाउँपालिका" },
          { name_en: "Harinas Rural Municipality", name_ne: "हरिनास गाउँपालिका" },
          { name_en: "Kaligandaki Rural Municipality", name_ne: "कालीगण्डकी गाउँपालिका" },
          { name_en: "Phedikhola Rural Municipality", name_ne: "फेदीखोला गाउँपालिका" },
        ],
      },
      {
        name_en: "Kaski",
        name_ne: "कास्की",
        municipalities: [
          { name_en: "Pokhara Metropolitan City", name_ne: "पोखरा महानगरपालिका" },
          { name_en: "Annapurna Rural Municipality", name_ne: "अन्नपूर्ण गाउँपालिका" },
          { name_en: "Machhapuchhre Rural Municipality", name_ne: "माछापुच्छ्रे गाउँपालिका" },
          { name_en: "Madi Rural Municipality", name_ne: "मादी गाउँपालिका" },
          { name_en: "Rupa Rural Municipality", name_ne: "रुपा गाउँपालिका" },
        ],
      },
      {
        name_en: "Manang",
        name_ne: "मनाङ",
        municipalities: [
          { name_en: "Chame Rural Municipality", name_ne: "चामे गाउँपालिका" },
          { name_en: "Narshon Rural Municipality", name_ne: "नार्सोन गाउँपालिका" },
          { name_en: "Neshyang Rural Municipality", name_ne: "नेस्याङ गाउँपालिका" },
          { name_en: "Manang Ngisyang Rural Municipality", name_ne: "मनाङ डिस्याङ गाउँपालिका" },
        ],
      },
      {
        name_en: "Mustang",
        name_ne: "मुस्ताङ",
        municipalities: [
          { name_en: "Gharapjhong Rural Municipality", name_ne: "घरपझोङ गाउँपालिका" },
          { name_en: "Thasang Rural Municipality", name_ne: "थासाङ गाउँपालिका" },
          { name_en: "Baragung Muktichhetra Rural Municipality", name_ne: "बारागुङ मुक्तिक्षेत्र गाउँपालिका" },
          { name_en: "Lomanthang Rural Municipality", name_ne: "लोमन्थाङ गाउँपालिका" },
          { name_en: "Dalome Rural Municipality", name_ne: "दालोमे गाउँपालिका" },
        ],
      },
      {
        name_en: "Myagdi",
        name_ne: "म्याग्दी",
        municipalities: [
          { name_en: "Beni Municipality", name_ne: "बेनी नगरपालिका" },
          { name_en: "Annapurna Rural Municipality", name_ne: "अन्नपूर्ण गाउँपालिका" },
          { name_en: "Dhaulagiri Rural Municipality", name_ne: "धवलागिरी गाउँपालिका" },
          { name_en: "Malika Rural Municipality", name_ne: "मालिका गाउँपालिका" },
          { name_en: "Mangala Rural Municipality", name_ne: "मंगला गाउँपालिका" },
          { name_en: "Raghuganga Rural Municipality", name_ne: "रघुगंगा गाउँपालिका" },
        ],
      },
      {
        name_en: "Parbat",
        name_ne: "पर्वत",
        municipalities: [
          { name_en: "Kushma Municipality", name_ne: "कुश्मा नगरपालिका" },
          { name_en: "Phalewas Municipality", name_ne: "फलेवास नगरपालिका" },
          { name_en: "Jaljala Rural Municipality", name_ne: "जलजला गाउँपालिका" },
          { name_en: "Mahashila Rural Municipality", name_ne: "महाशिला गाउँपालिका" },
          { name_en: "Modi Rural Municipality", name_ne: "मोदी गाउँपालिका" },
          { name_en: "Paiyun Rural Municipality", name_ne: "पैयूँ गाउँपालिका" },
          { name_en: "Bihadi Rural Municipality", name_ne: "विहादी गाउँपालिका" },
        ],
      },
      {
        name_en: "Baglung",
        name_ne: "बाग्लुङ",
        municipalities: [
          { name_en: "Baglung Municipality", name_ne: "बाग्लुङ नगरपालिका" },
          { name_en: "Galkot Municipality", name_ne: "गल्कोट नगरपालिका" },
          { name_en: "Jaimini Municipality", name_ne: "जैमिनी नगरपालिका" },
          { name_en: "Dhorpatan Municipality", name_ne: "ढोरपाटन नगरपालिका" },
          { name_en: "Bareng Rural Municipality", name_ne: "बरेङ गाउँपालिका" },
          { name_en: "Kag Rural Municipality", name_ne: "काग गाउँपालिका" },
          { name_en: "Nisikhola Rural Municipality", name_ne: "निसीखोला गाउँपालिका" },
          { name_en: "Taman Khola Rural Municipality", name_ne: "तमान खोला गाउँपालिका" },
          { name_en: "Tara Khola Rural Municipality", name_ne: "तारा खोला गाउँपालिका" },
          { name_en: "Kanthekhola Rural Municipality", name_ne: "काठेखोला गाउँपालिका" },
        ],
      },
      {
        name_en: "Nawalpur",
        name_ne: "नवलपुर",
        municipalities: [
          { name_en: "Kawasoti Municipality", name_ne: "कावासोती नगरपालिका" },
          { name_en: "Gaindakot Municipality", name_ne: "गैँडाकोट नगरपालिका" },
          { name_en: "Madhyabindu Municipality", name_ne: "मध्यबिन्दु नगरपालिका" },
          { name_en: "Devchuli Municipality", name_ne: "देवचुली नगरपालिका" },
          { name_en: "Binayi Triveni Rural Municipality", name_ne: "विनयी त्रिवेणी गाउँपालिका" },
          { name_en: "Bulingtar Rural Municipality", name_ne: "बुलिङटार गाउँपालिका" },
          { name_en: "Hupsekot Rural Municipality", name_ne: "हुप्सेकोट गाउँपालिका" },
          { name_en: "Baudikali Rural Municipality", name_ne: "बौदीकाली गाउँपालिका" },
        ],
      },
    ],
  },
  {
    name_en: "Lumbini Province",
    name_ne: "लुम्बिनी प्रदेश",
    districts: [
      {
        name_en: "Gulmi",
        name_ne: "गुल्मी",
        municipalities: [
          { name_en: "Musikot Municipality", name_ne: "मुसिकोट नगरपालिका" },
          { name_en: "Resunga Municipality", name_ne: "रेसुङ्गा नगरपालिका" },
          { name_en: "Isma Rural Municipality", name_ne: "ईस्मा गाउँपालिका" },
          { name_en: "Chandrakot Rural Municipality", name_ne: "चन्द्रकोट गाउँपालिका" },
          { name_en: "Chatrakot Rural Municipality", name_ne: "छत्रकोट गाउँपालिका" },
          { name_en: "Dhurkot Rural Municipality", name_ne: "धुर्कोट गाउँपालिका" },
          { name_en: "Gulmi Darbar Rural Municipality", name_ne: "गुल्मी दरबार गाउँपालिका" },
          { name_en: "Kaligandaki Rural Municipality", name_ne: "कालीगण्डकी गाउँपालिका" },
          { name_en: "Madane Rural Municipality", name_ne: "मदाने गाउँपालिका" },
          { name_en: "Malika Rural Municipality", name_ne: "मालिका गाउँपालिका" },
          { name_en: "Ruru Rural Municipality", name_ne: "रुरु गाउँपालिका" },
          { name_en: "Satyawati Rural Municipality", name_ne: "सत्यवती गाउँपालिका" },
        ],
      },
      {
        name_en: "Palpa",
        name_ne: "पाल्पा",
        municipalities: [
          { name_en: "Tansen Municipality", name_ne: "तानसेन नगरपालिका" },
          { name_en: "Rampur Municipality", name_ne: "रामपुर नगरपालिका" },
          { name_en: "Bagnaskali Rural Municipality", name_ne: "बगनासकाली गाउँपालिका" },
          { name_en: "Mathagadhi Rural Municipality", name_ne: "माथागढी गाउँपालिका" },
          { name_en: "Nisdi Rural Municipality", name_ne: "निस्दी गाउँपालिका" },
          { name_en: "Purbakhola Rural Municipality", name_ne: "पूर्वखोला गाउँपालिका" },
          { name_en: "Rainadevi Chhahara Rural Municipality", name_ne: "रैनादेवी छहरा गाउँपालिका" },
          { name_en: "Ribdikot Rural Municipality", name_ne: "रिब्दीकोट गाउँपालिका" },
          { name_en: "Tinau Rural Municipality", name_ne: "तिनाउ गाउँपालिका" },
          { name_en: "Tribeni Rural Municipality", name_ne: "त्रिवेणी गाउँपालिका" },
        ],
      },
      {
        name_en: "Parasi",
        name_ne: "परासी",
        municipalities: [
          { name_en: "Bardaghat Municipality", name_ne: "बर्दघाट नगरपालिका" },
          { name_en: "Ramgram Municipality", name_ne: "रामग्राम नगरपालिका" },
          { name_en: "Sunwal Municipality", name_ne: "सुनवल नगरपालिका" },
          { name_en: "Susta Rural Municipality", name_ne: "सुस्ता गाउँपालिका" },
          { name_en: "Palhinandan Rural Municipality", name_ne: "पल्हिनन्दन गाउँपालिका" },
          { name_en: "Pratappur Rural Municipality", name_ne: "प्रतापपुर गाउँपालिका" },
          { name_en: "Sarawal Rural Municipality", name_ne: "सरावल गाउँपालिका" },
        ],
      },
      {
        name_en: "Rupandehi",
        name_ne: "रुपन्देही",
        municipalities: [
          { name_en: "Butwal Sub-Metropolitan City", name_ne: "बुटवल उपमहानगरपालिका" },
          { name_en: "Siddharthanagar Municipality", name_ne: "सिद्धार्थनगर नगरपालिका" },
          { name_en: "Devdaha Municipality", name_ne: "देवदह नगरपालिका" },
          { name_en: "Lumbini Sanskritik Municipality", name_ne: "लुम्बिनी सांस्कृतिक नगरपालिका" },
          { name_en: "Sainamaina Municipality", name_ne: "सैनामैना नगरपालिका" },
          { name_en: "Tilottama Municipality", name_ne: "तिलोत्तमा नगरपालिका" },
          { name_en: "Gaidahawa Rural Municipality", name_ne: "गैडहवा गाउँपालिका" },
          { name_en: "Kanchan Rural Municipality", name_ne: "कन्चन गाउँपालिका" },
          { name_en: "Kotahimai Rural Municipality", name_ne: "कोटहीमाई गाउँपालिका" },
          { name_en: "Marchawari Rural Municipality", name_ne: "मर्चवारी गाउँपालिका" },
          { name_en: "Mayadevi Rural Municipality", name_ne: "मायादेवी गाउँपालिका" },
          { name_en: "Omsatiya Rural Municipality", name_ne: "ओम्सतिया गाउँपालिका" },
          { name_en: "Rohini Rural Municipality", name_ne: "रोहिणी गाउँपालिका" },
          { name_en: "Sammarimai Rural Municipality", name_ne: "सम्मरीमाई गाउँपालिका" },
          { name_en: "Siyari Rural Municipality", name_ne: "सियारी गाउँपालिका" },
          { name_en: "Suddhodhan Rural Municipality", name_ne: "शुद्धोधन गाउँपालिका" },
        ],
      },
      {
        name_en: "Kapilvastu",
        name_ne: "कपिलवस्तु",
        municipalities: [
          { name_en: "Kapilvastu Municipality", name_ne: "कपिलवस्तु नगरपालिका" },
          { name_en: "Buddhabhumi Municipality", name_ne: "बुद्धभूमि नगरपालिका" },
          { name_en: "Shivaraj Municipality", name_ne: "शिवराज नगरपालिका" },
          { name_en: "Maharajgunj Municipality", name_ne: "महाराजगंज नगरपालिका" },
          { name_en: "Krishnanagar Municipality", name_ne: "कृष्णनगर नगरपालिका" },
          { name_en: "Banganga Municipality", name_ne: "बाणगंगा नगरपालिका" },
          { name_en: "Bijaynagar Rural Municipality", name_ne: "विजयनगर गाउँपालिका" },
          { name_en: "Mayadevi Rural Municipality", name_ne: "मायादेवी गाउँपालिका" },
          { name_en: "Suddhodhan Rural Municipality", name_ne: "शुद्धोधन गाउँपालिका" },
          { name_en: "Yashodhara Rural Municipality", name_ne: "यशोधरा गाउँपालिका" },
        ],
      },
      {
        name_en: "Arghakhanchi",
        name_ne: "अर्घाखाँची",
        municipalities: [
          { name_en: "Sandhikharka Municipality", name_ne: "सन्धिखर्क नगरपालिका" },
          { name_en: "Sitganga Municipality", name_ne: "सीतगंगा नगरपालिका" },
          { name_en: "Bhumikasthan Municipality", name_ne: "भूमिकास्थान नगरपालिका" },
          { name_en: "Chhatradev Rural Municipality", name_ne: "छत्रदेव गाउँपालिका" },
          { name_en: "Malarani Rural Municipality", name_ne: "मालारानी गाउँपालिका" },
          { name_en: "Panini Rural Municipality", name_ne: "पाणिनी गाउँपालिका" },
        ],
      },
      {
        name_en: "Pyuthan",
        name_ne: "प्यूठान",
        municipalities: [
          { name_en: "Pyuthan Municipality", name_ne: "प्यूठान नगरपालिका" },
          { name_en: "Swargadwari Municipality", name_ne: "स्वर्गद्वारी नगरपालिका" },
          { name_en: "Gaumukhi Rural Municipality", name_ne: "गौमुखी गाउँपालिका" },
          { name_en: "Jhimruk Rural Municipality", name_ne: "झिमरुक गाउँपालिका" },
          { name_en: "Mandavi Rural Municipality", name_ne: "मण्डवी गाउँपालिका" },
          { name_en: "Mallarani Rural Municipality", name_ne: "मल्लरानी गाउँपालिका" },
          { name_en: "Naubahini Rural Municipality", name_ne: "नौबहिनी गाउँपालिका" },
          { name_en: "Sarumarani Rural Municipality", name_ne: "सरुमारानी गाउँपालिका" },
          { name_en: "Airawati Rural Municipality", name_ne: "ऐरावती गाउँपालिका" },
        ],
      },
      {
        name_en: "Rolpa",
        name_ne: "रोल्पा",
        municipalities: [
          { name_en: "Rolpa Municipality", name_ne: "रोल्पा नगरपालिका" },
          { name_en: "Triveni Rural Municipality", name_ne: "त्रिवेणी गाउँपालिका" },
          { name_en: "Duikholi Rural Municipality", name_ne: "दुईखोली गाउँपालिका" },
          { name_en: "Gangadevi Rural Municipality", name_ne: "गंगादेवी गाउँपालिका" },
          { name_en: "Lungri Rural Municipality", name_ne: "लुंग्री गाउँपालिका" },
          { name_en: "Madi Rural Municipality", name_ne: "मादी गाउँपालिका" },
          { name_en: "Runtigadhi Rural Municipality", name_ne: "रुन्टीगढी गाउँपालिका" },
          { name_en: "Sunchhahari Rural Municipality", name_ne: "सुनछहरी गाउँपालिका" },
          { name_en: "Suwarnabati Rural Municipality", name_ne: "सुवर्णबती गाउँपालिका" },
          { name_en: "Thawang Rural Municipality", name_ne: "थवाङ गाउँपालिका" },
        ],
      },
      {
        name_en: "Eastern Rukum",
        name_ne: "पूर्वी रुकुम",
        municipalities: [
          { name_en: "Bhume Rural Municipality", name_ne: "भूमे गाउँपालिका" },
          { name_en: "Putha Uttarganga Rural Municipality", name_ne: "पुठा उत्तरगंगा गाउँपालिका" },
          { name_en: "Sisne Rural Municipality", name_ne: "सिस्ने गाउँपालिका" },
        ],
      },
      {
        name_en: "Dang",
        name_ne: "दाङ",
        municipalities: [
          { name_en: "Ghorahi Sub-Metropolitan City", name_ne: "घोराही उपमहानगरपालिका" },
          { name_en: "Tulsipur Sub-Metropolitan City", name_ne: "तुल्सीपुर उपमहानगरपालिका" },
          { name_en: "Lamahi Municipality", name_ne: "लमही नगरपालिका" },
          { name_en: "Bangalachhuli Rural Municipality", name_ne: "बंगलाछुली गाउँपालिका" },
          { name_en: "Dangisharan Rural Municipality", name_ne: "दंगीशरण गाउँपालिका" },
          { name_en: "Gadhawa Rural Municipality", name_ne: "गढवा गाउँपालिका" },
          { name_en: "Rajpur Rural Municipality", name_ne: "राजपुर गाउँपालिका" },
          { name_en: "Rapti Rural Municipality", name_ne: "राप्ती गाउँपालिका" },
          { name_en: "Shantinagar Rural Municipality", name_ne: "शान्तिनगर गाउँपालिका" },
          { name_en: "Babai Rural Municipality", name_ne: "बबई गाउँपालिका" },
        ],
      },
      {
        name_en: "Banke",
        name_ne: "बाँके",
        municipalities: [
          { name_en: "Nepalgunj Sub-Metropolitan City", name_ne: "नेपालगंज उपमहानगरपालिका" },
          { name_en: "Kohalpur Municipality", name_ne: "कोहलपुर नगरपालिका" },
          { name_en: "Narainapur Rural Municipality", name_ne: "नरैनापुर गाउँपालिका" },
          { name_en: "Rapti Sonari Rural Municipality", name_ne: "राप्ती सोनारी गाउँपालिका" },
          { name_en: "Baijanath Rural Municipality", name_ne: "बैजनाथ गाउँपालिका" },
          { name_en: "Khajura Rural Municipality", name_ne: "खजुरा गाउँपालिका" },
          { name_en: "Duduwa Rural Municipality", name_ne: "डुडुवा गाउँपालिका" },
          { name_en: "Janaki Rural Municipality", name_ne: "जानकी गाउँपालिका" },
        ],
      },
      {
        name_en: "Bardiya",
        name_ne: "बर्दिया",
        municipalities: [
          { name_en: "Gulariya Municipality", name_ne: "गुलरिया नगरपालिका" },
          { name_en: "Rajapur Municipality", name_ne: "राजापुर नगरपालिका" },
          { name_en: "Madhuwan Municipality", name_ne: "मधुवन नगरपालिका" },
          { name_en: "Thakurbaba Municipality", name_ne: "ठाकुरबाबा नगरपालिका" },
          { name_en: "Bansgadhi Municipality", name_ne: "बाँसगढी नगरपालिका" },
          { name_en: "Barbardiya Municipality", name_ne: "बारबर्दिया नगरपालिका" },
          { name_en: "Badhaiyatal Rural Municipality", name_ne: "बढैयाताल गाउँपालिका" },
          { name_en: "Geruwa Rural Municipality", name_ne: "गेरुवा गाउँपालिका" },
        ],
      },
    ],
  },
  {
    name_en: "Karnali Province",
    name_ne: "कर्णाली प्रदेश",
    districts: [
      {
        name_en: "Western Rukum",
        name_ne: "पश्चिमी रुकुम",
        municipalities: [
          { name_en: "Musikot Municipality", name_ne: "मुसिकोट नगरपालिका" },
          { name_en: "Chaurjahari Municipality", name_ne: "चौरजहारी नगरपालिका" },
          { name_en: "Aathbiskot Municipality", name_ne: "आठबिसकोट नगरपालिका" },
          { name_en: "Banfikot Rural Municipality", name_ne: "बाँफिकोट गाउँपालिका" },
          { name_en: "Sani Bheri Rural Municipality", name_ne: "सानी भेरी गाउँपालिका" },
          { name_en: "Tribeni Rural Municipality", name_ne: "त्रिवेणी गाउँपालिका" },
        ],
      },
      {
        name_en: "Salyan",
        name_ne: "सल्यान",
        municipalities: [
          { name_en: "Shaarda Municipality", name_ne: "शारदा नगरपालिका" },
          { name_en: "Bangad Kupinde Municipality", name_ne: "बनगाड कुपिण्डे नगरपालिका" },
          { name_en: "Bagchaur Municipality", name_ne: "बागचौर नगरपालिका" },
          { name_en: "Chhatreshwori Rural Municipality", name_ne: "छत्रेश्वरी गाउँपालिका" },
          { name_en: "Darma Rural Municipality", name_ne: "दार्मा गाउँपालिका" },
          { name_en: "Kalimati Rural Municipality", name_ne: "कालीमाटी गाउँपालिका" },
          { name_en: "Kapurkot Rural Municipality", name_ne: "कपुरकोट गाउँपालिका" },
          { name_en: "Kumakh Rural Municipality", name_ne: "कुमाख गाउँपालिका" },
          { name_en: "Siddha Kumakh Rural Municipality", name_ne: "सिद्ध कुमाख गाउँपालिका" },
          { name_en: "Tribeni Rural Municipality", name_ne: "त्रिवेणी गाउँपालिका" },
        ],
      },
      {
        name_en: "Dolpa",
        name_ne: "डोल्पा",
        municipalities: [
          { name_en: "Thuli Bheri Municipality", name_ne: "ठुली भेरी नगरपालिका" },
          { name_en: "Tripurasundari Municipality", name_ne: "त्रिपुरासुन्दरी नगरपालिका" },
          { name_en: "Dolpo Buddha Rural Municipality", name_ne: "डोल्पो बुद्ध गाउँपालिका" },
          { name_en: "She Phoksundo Rural Municipality", name_ne: "शे फोक्सुण्डो गाउँपालिका" },
          { name_en: "Jagadulla Rural Municipality", name_ne: "जगदुल्ला गाउँपालिका" },
          { name_en: "Mudkechula Rural Municipality", name_ne: "मुड्केचुला गाउँपालिका" },
          { name_en: "Kaike Rural Municipality", name_ne: "काइके गाउँपालिका" },
          { name_en: "Chharka Tangsong Rural Municipality", name_ne: "छार्का ताङसोङ गाउँपालिका" },
        ],
      },
      {
        name_en: "Humla",
        name_ne: "हुम्ला",
        municipalities: [
          { name_en: "Simikot Rural Municipality", name_ne: "सिमकोट गाउँपालिका" },
          { name_en: "Namkha Rural Municipality", name_ne: "नाम्खा गाउँपालिका" },
          { name_en: "Kharpunath Rural Municipality", name_ne: "खार्पुनाथ गाउँपालिका" },
          { name_en: "Sarkegad Rural Municipality", name_ne: "सर्केगाड गाउँपालिका" },
          { name_en: "Chankheli Rural Municipality", name_ne: "चंखेली गाउँपालिका" },
          { name_en: "Adanchuli Rural Municipality", name_ne: "अदानचुली गाउँपालिका" },
          { name_en: "Tanjakot Rural Municipality", name_ne: "ताँजाकोट गाउँपालिका" },
        ],
      },
      {
        name_en: "Jumla",
        name_ne: "जुम्ला",
        municipalities: [
          { name_en: "Chandannath Municipality", name_ne: "चन्दननाथ नगरपालिका" },
          { name_en: "Guthichaur Rural Municipality", name_ne: "गुठिचौर गाउँपालिका" },
          { name_en: "Hima Rural Municipality", name_ne: "हिमा गाउँपालिका" },
          { name_en: "Kanaka Sundari Rural Municipality", name_ne: "कनकासुन्दरी गाउँपालिका" },
          { name_en: "Patarasi Rural Municipality", name_ne: "पातारासी गाउँपालिका" },
          { name_en: "Sinja Rural Municipality", name_ne: "सिंजा गाउँपालिका" },
          { name_en: "Tila Rural Municipality", name_ne: "तिला गाउँपालिका" },
          { name_en: "Tatopani Rural Municipality", name_ne: "तातोपानी गाउँपालिका" },
        ],
      },
      {
        name_en: "Kalikot",
        name_ne: "कालिकोट",
        municipalities: [
          { name_en: "Khandachakra Municipality", name_ne: "खाँडाचक्र नगरपालिका" },
          { name_en: "Raskot Municipality", name_ne: "रास्कोट नगरपालिका" },
          { name_en: "Tilagufa Municipality", name_ne: "तिलागुफा नगरपालिका" },
          { name_en: "Pachaljharana Rural Municipality", name_ne: "पचालझरना गाउँपालिका" },
          { name_en: "Palata Rural Municipality", name_ne: "पलाता गाउँपालिका" },
          { name_en: "Shubha Kalika Rural Municipality", name_ne: "शुभ कालिका गाउँपालिका" },
          { name_en: "Sanni Triveni Rural Municipality", name_ne: "सान्नी त्रिवेणी गाउँपालिका" },
          { name_en: "Narharinath Rural Municipality", name_ne: "नरहरिनाथ गाउँपालिका" },
          { name_en: "Mahawai Rural Municipality", name_ne: "महावै गाउँपालिका" },
        ],
      },
      {
        name_en: "Mugu",
        name_ne: "मुगु",
        municipalities: [
          { name_en: "Chhayanath Rara Municipality", name_ne: "छायाँनाथ रारा नगरपालिका" },
          { name_en: "Khamira Rural Municipality", name_ne: "खाम्रिरा गाउँपालिका" },
          { name_en: "Mugum Karmarong Rural Municipality", name_ne: "मुगुम कार्मारोंग गाउँपालिका" },
          { name_en: "Soru Rural Municipality", name_ne: "सोरु गाउँपालिका" },
        ],
      },
      {
        name_en: "Surkhet",
        name_ne: "सुर्खेत",
        municipalities: [
          { name_en: "Birendranagar Municipality", name_ne: "वीरेन्द्रनगर नगरपालिका" },
          { name_en: "Bheriganga Municipality", name_ne: "भेरीगंगा नगरपालिका" },
          { name_en: "Gurbhakot Municipality", name_ne: "गुर्भाकोट नगरपालिका" },
          { name_en: "Panchpuri Municipality", name_ne: "पञ्चपुरी नगरपालिका" },
          { name_en: "Lekbeshi Municipality", name_ne: "लेकबेशी नगरपालिका" },
          { name_en: "Barahatal Rural Municipality", name_ne: "बराहताल गाउँपालिका" },
          { name_en: "Chaukune Rural Municipality", name_ne: "चौकुने गाउँपालिका" },
          { name_en: "Chingad Rural Municipality", name_ne: "चिंगाड गाउँपालिका" },
          { name_en: "Simta Rural Municipality", name_ne: "सिम्ता गाउँपालिका" },
        ],
      },
      {
        name_en: "Dailekh",
        name_ne: "दैलेख",
        municipalities: [
          { name_en: "Narayan Municipality", name_ne: "नारायण नगरपालिका" },
          { name_en: "Dullu Municipality", name_ne: "दुल्लु नगरपालिका" },
          { name_en: "Chamunda Bindrasaini Municipality", name_ne: "चामुण्डा बिन्द्रासैनी नगरपालिका" },
          { name_en: "Aathbis Municipality", name_ne: "आठबीस नगरपालिका" },
          { name_en: "Bhagawatimai Rural Municipality", name_ne: "भगवतीमाई गाउँपालिका" },
          { name_en: "Bhairabi Rural Municipality", name_ne: "भैरवी गाउँपालिका" },
          { name_en: "Dungeshwor Rural Municipality", name_ne: "डुंगेश्वर गाउँपालिका" },
          { name_en: "Gurans Rural Municipality", name_ne: "गुराँस गाउँपालिका" },
          { name_en: "Mahabu Rural Municipality", name_ne: "महाबु गाउँपालिका" },
          { name_en: "Naumule Rural Municipality", name_ne: "नौमूले गाउँपालिका" },
          { name_en: "Thantikandh Rural Municipality", name_ne: "ठाँटीकाँध गाउँपालिका" },
        ],
      },
      {
        name_en: "Jajarkot",
        name_ne: "जाजरकोट",
        municipalities: [
          { name_en: "Bheri Municipality", name_ne: "भेरी नगरपालिका" },
          { name_en: "Chhedagad Municipality", name_ne: "छेडागाड नगरपालिका" },
          { name_en: "Nalgad Municipality", name_ne: "नलगाड नगरपालिका" },
          { name_en: "Junichande Rural Municipality", name_ne: "जुनीचाँदे गाउँपालिका" },
          { name_en: "Kushe Rural Municipality", name_ne: "कुसे गाउँपालिका" },
          { name_en: "Barekot Rural Municipality", name_ne: "बारेकोट गाउँपालिका" },
          { name_en: "Shivalaya Rural Municipality", name_ne: "शिवालय गाउँपालिका" },
        ],
      },
    ],
  },
  {
    name_en: "Sudurpashchim Province",
    name_ne: "सुदूरपश्चिम प्रदेश",
    districts: [
      {
        name_en: "Bajura",
        name_ne: "बाजुरा",
        municipalities: [
          { name_en: "Badimalika Municipality", name_ne: "बडीमालिका नगरपालिका" },
          { name_en: "Triveni Municipality", name_ne: "त्रिवेणी नगरपालिका" },
          { name_en: "Budhiganga Municipality", name_ne: "बुढीगंगा नगरपालिका" },
          { name_en: "Budhinanda Municipality", name_ne: "बूढीनन्दा नगरपालिका" },
          { name_en: "Gaumul Rural Municipality", name_ne: "गौमुल गाउँपालिका" },
          { name_en: "Himali Rural Municipality", name_ne: "हिमाली गाउँपालिका" },
          { name_en: "Khaptad Chhanna Rural Municipality", name_ne: "खप्तड छान्ना गाउँपालिका" },
          { name_en: "Jagannath Rural Municipality", name_ne: "जगन्नाथ गाउँपालिका" },
          { name_en: "Swamikartik Khapar Rural Municipality", name_ne: "स्वामीकार्तिक खापर गाउँपालिका" },
        ],
      },
      {
        name_en: "Bajhang",
        name_ne: "बझाङ",
        municipalities: [
          { name_en: "Jayaprithvi Municipality", name_ne: "जयपृथ्वी नगरपालिका" },
          { name_en: "Bungal Municipality", name_ne: "बुंगल नगरपालिका" },
          { name_en: "Talkot Rural Municipality", name_ne: "तल्कोट गाउँपालिका" },
          { name_en: "Masta Rural Municipality", name_ne: "मष्टा गाउँपालिका" },
          { name_en: "Khaptad Rural Municipality", name_ne: "खप्तड गाउँपालिका" },
          { name_en: "Thalara Rural Municipality", name_ne: "थलारा गाउँपालिका" },
          { name_en: "Bitthadchir Rural Municipality", name_ne: "बित्थडचिर गाउँपालिका" },
          { name_en: "Surma Rural Municipality", name_ne: "सूर्मा गाउँपालिका" },
          { name_en: "Chhabis Pathibhera Rural Municipality", name_ne: "छब्बीस पाथिभेरा गाउँपालिका" },
          { name_en: "Durgathali Rural Municipality", name_ne: "दुर्गाथली गाउँपालिका" },
          { name_en: "Kedarseu Rural Municipality", name_ne: "केदारस्यु गाउँपालिका" },
          { name_en: "Saipal Rural Municipality", name_ne: "सैपाल गाउँपालिका" },
        ],
      },
      {
        name_en: "Darchula",
        name_ne: "दार्चुला",
        municipalities: [
          { name_en: "Mahakali Municipality", name_ne: "महाकाली नगरपालिका" },
          { name_en: "Shailyashikhar Municipality", name_ne: "शैल्यशिखर नगरपालिका" },
          { name_en: "Apihimal Rural Municipality", name_ne: "अपिहिमाल गाउँपालिका" },
          { name_en: "Byas Rural Municipality", name_ne: "ब्यास गाउँपालिका" },
          { name_en: "Duhun Rural Municipality", name_ne: "दुहुँ गाउँपालिका" },
          { name_en: "Lekam Rural Municipality", name_ne: "लेकम गाउँपालिका" },
          { name_en: "Malikarjun Rural Municipality", name_ne: "मालिकार्जुन गाउँपालिका" },
          { name_en: "Marma Rural Municipality", name_ne: "मार्मा गाउँपालिका" },
          { name_en: "Naugad Rural Municipality", name_ne: "नौगाड गाउँपालिका" },
        ],
      },
      {
        name_en: "Baitadi",
        name_ne: "बैतडी",
        municipalities: [
          { name_en: "Dasharathchand Municipality", name_ne: "दशरथचन्द नगरपालिका" },
          { name_en: "Patan Municipality", name_ne: "पाटन नगरपालिका" },
          { name_en: "Melauli Municipality", name_ne: "मेलौली नगरपालिका" },
          { name_en: "Purchaudi Municipality", name_ne: "पुर्चौडी नगरपालिका" },
          { name_en: "Dogdakedar Rural Municipality", name_ne: "दोगडाकेदार गाउँपालिका" },
          { name_en: "Dilasaini Rural Municipality", name_ne: "दिलासैनी गाउँपालिका" },
          { name_en: "Pancheshwar Rural Municipality", name_ne: "पञ्चेश्वर गाउँपालिका" },
          { name_en: "Shivanath Rural Municipality", name_ne: "शिवनाथ गाउँपालिका" },
          { name_en: "Sigas Rural Municipality", name_ne: "सिगास गाउँपालिका" },
          { name_en: "Surnaya Rural Municipality", name_ne: "सुर्नया गाउँपालिका" },
        ],
      },
      {
        name_en: "Dadeldhura",
        name_ne: "डडेल्धुरा",
        municipalities: [
          { name_en: "Amargadhi Municipality", name_ne: "अमरगढी नगरपालिका" },
          { name_en: "Parashuram Municipality", name_ne: "परशुराम नगरपालिका" },
          { name_en: "Aalital Rural Municipality", name_ne: "आलिताल गाउँपालिका" },
          { name_en: "Ajaymeru Rural Municipality", name_ne: "अजयमेरु गाउँपालिका" },
          { name_en: "Bhageshwar Rural Municipality", name_ne: "भागेश्वर गाउँपालिका" },
          { name_en: "Ganyapadhura Rural Municipality", name_ne: "गन्यापधुरा गाउँपालिका" },
          { name_en: "Navadurga Rural Municipality", name_ne: "नवदुर्गा गाउँपालिका" },
        ],
      },
      {
        name_en: "Doti",
        name_ne: "डोटी",
        municipalities: [
          { name_en: "Dipayal Silgadhi Municipality", name_ne: "दिपायल सिलगढी नगरपालिका" },
          { name_en: "Shikhar Municipality", name_ne: "शिखर नगरपालिका" },
          { name_en: "Aadarsha Rural Municipality", name_ne: "आदर्श गाउँपालिका" },
          { name_en: "Badikedar Rural Municipality", name_ne: "बडीकेदार गाउँपालिका" },
          { name_en: "Bogatan-Phudsil Rural Municipality", name_ne: "बोगटान-फुड्सिल गाउँपालिका" },
          { name_en: "Jorayal Rural Municipality", name_ne: "जोरायल गाउँपालिका" },
          { name_en: "KI Singh Rural Municipality", name_ne: "के.आई.सिंह गाउँपालिका" },
          { name_en: "Purbichauki Rural Municipality", name_ne: "पूर्वीचौकी गाउँपालिका" },
          { name_en: "Sayal Rural Municipality", name_ne: "सायल गाउँपालिका" },
        ],
      },
      {
        name_en: "Achham",
        name_ne: "अछाम",
        municipalities: [
          { name_en: "Mangalsen Municipality", name_ne: "मंगलसेन नगरपालिका" },
          { name_en: "Sanfebagar Municipality", name_ne: "साँफेबगर नगरपालिका" },
          { name_en: "Kamalbazar Municipality", name_ne: "कमलबजार नगरपालिका" },
          { name_en: "Panchadewal Binayak Municipality", name_ne: "पञ्चदेवल विनायक नगरपालिका" },
          { name_en: "Bannigadhi Jayagadh Rural Municipality", name_ne: "बान्नीगढी जयगढ गाउँपालिका" },
          { name_en: "Chaurpati Rural Municipality", name_ne: "चौरपाटी गाउँपालिका" },
          { name_en: "Dhakari Rural Municipality", name_ne: "ढकारी गाउँपालिका" },
          { name_en: "Mellekh Rural Municipality", name_ne: "मेल्लेख गाउँपालिका" },
          { name_en: "Ramaroshan Rural Municipality", name_ne: "रामारोशन गाउँपालिका" },
          { name_en: "Turmakhand Rural Municipality", name_ne: "तुर्माखाँद गाउँपालिका" },
        ],
      },
      {
        name_en: "Kailali",
        name_ne: "कैलाली",
        municipalities: [
          { name_en: "Dhangadhi Sub-Metropolitan City", name_ne: "धनगढी उपमहानगरपालिका" },
          { name_en: "Tikapur Municipality", name_ne: "टीकापुर नगरपालिका" },
          { name_en: "Ghodaghodi Municipality", name_ne: "घोडाघोडी नगरपालिका" },
          { name_en: "Lamkichuha Municipality", name_ne: "लम्कीचुहा नगरपालिका" },
          { name_en: "Bhajani Municipality", name_ne: "भजनी नगरपालिका" },
          { name_en: "Godawari Municipality", name_ne: "गोदावरी नगरपालिका" },
          { name_en: "Gauriganga Municipality", name_ne: "गौरीगंगा नगरपालिका" },
          { name_en: "Bardagoriya Rural Municipality", name_ne: "बर्डगोरिया गाउँपालिका" },
          { name_en: "Mohanyal Rural Municipality", name_ne: "मोहन्याल गाउँपालिका" },
          { name_en: "Janaki Rural Municipality", name_ne: "जानकी गाउँपालिका" },
          { name_en: "Kailari Rural Municipality", name_ne: "कैलारी गाउँपालिका" },
          { name_en: "Joshipur Rural Municipality", name_ne: "जोशीपुर गाउँपालिका" },
          { name_en: "Chure Rural Municipality", name_ne: "चुरे गाउँपालिका" },
        ],
      },
      {
        name_en: "Kanchanpur",
        name_ne: "कञ्चनपुर",
        municipalities: [
          { name_en: "Bhimdatta Municipality", name_ne: "भीमदत्त नगरपालिका" },
          { name_en: "Punarbas Municipality", name_ne: "पुनर्वास नगरपालिका" },
          { name_en: "Bedkot Municipality", name_ne: "बेदकोट नगरपालिका" },
          { name_en: "Mahakali Municipality", name_ne: "महाकाली नगरपालिका" },
          { name_en: "Shuklaphanta Municipality", name_ne: "शुक्लाफाँटा नगरपालिका" },
          { name_en: "Belauri Municipality", name_ne: "बेलौरी नगरपालिका" },
          { name_en: "Krishnapur Municipality", name_ne: "कृष्णपुर नगरपालिका" },
          { name_en: "Beldandi Rural Municipality", name_ne: "बेल्डाँडी गाउँपालिका" },
          { name_en: "Laljhadi Rural Municipality", name_ne: "लालझाडी गाउँपालिका" },
        ],
      },
    ],
  },
];

// Helper functions for cascading lookups

export function getDistricts(provinceNameEn: string): District[] {
  const province = NEPAL_PROVINCES.find((p) => p.name_en === provinceNameEn);
  return province?.districts ?? [];
}

export function getMunicipalities(districtNameEn: string): Municipality[] {
  for (const province of NEPAL_PROVINCES) {
    const district = province.districts.find((d) => d.name_en === districtNameEn);
    if (district) return district.municipalities;
  }
  return [];
}

export function findDistrictNepali(districtNameEn: string): string | null {
  for (const province of NEPAL_PROVINCES) {
    const district = province.districts.find((d) => d.name_en === districtNameEn);
    if (district) return district.name_ne;
  }
  return null;
}

export function findMunicipalityNepali(municipalityNameEn: string): string | null {
  for (const province of NEPAL_PROVINCES) {
    for (const district of province.districts) {
      const muni = district.municipalities.find((m) => m.name_en === municipalityNameEn);
      if (muni) return muni.name_ne;
    }
  }
  return null;
}

export function findProvinceForDistrict(districtNameEn: string): string | null {
  for (const province of NEPAL_PROVINCES) {
    if (province.districts.some((d) => d.name_en === districtNameEn)) {
      return province.name_en;
    }
  }
  return null;
}
