"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { useRouter } from "next/navigation";
import { api, ApiError } from "@/lib/api-client";
import type { Company, CompanyType } from "@/types/models";
import { COMPANY_TYPE_LABELS } from "@/types/models";
import {
  NEPAL_PROVINCES,
  getDistricts,
  getMunicipalities,
  findDistrictNepali,
  findMunicipalityNepali,
  findProvinceForDistrict,
} from "@/lib/nepal-locations";
import { transliterateToNepali } from "@/lib/transliterate";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Building2Icon,
  MapPinIcon,
  LandmarkIcon,
  PhoneIcon,
  ShieldCheckIcon,
  Loader2Icon,
  SparklesIcon,
} from "lucide-react";
import { NepaliInput } from "@/components/nepali-input";

interface CompanyFormProps {
  company?: Company;
}

type FormData = Record<string, string>;

const COMPANY_TYPES = Object.entries(COMPANY_TYPE_LABELS) as [
  CompanyType,
  string,
][];

export function CompanyForm({ company }: CompanyFormProps) {
  const router = useRouter();
  const [submitting, setSubmitting] = useState(false);
  const [errors, setErrors] = useState<Record<string, string[]>>({});
  const [transliterating, setTransliterating] = useState(false);
  const transliterateTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Derive province from district for edit mode
  const initialProvince = company?.district_en
    ? findProvinceForDistrict(company.district_en) ?? ""
    : "";

  const [selectedProvince, setSelectedProvince] = useState(initialProvince);

  const [form, setForm] = useState<FormData>({
    name_en: company?.name_en ?? "",
    name_ne: company?.name_ne ?? "",
    registration_number: company?.registration_number ?? "",
    pan_number: company?.pan_number ?? "",
    vat_number: company?.vat_number ?? "",
    company_type: company?.company_type ?? "pvt_ltd",
    incorporation_date: company?.incorporation_date ?? "",
    district_en: company?.district_en ?? "",
    district_ne: company?.district_ne ?? "",
    municipality_en: company?.municipality_en ?? "",
    municipality_ne: company?.municipality_ne ?? "",
    ward: company?.ward ?? "",
    tole_en: company?.tole_en ?? "",
    tole_ne: company?.tole_ne ?? "",
    authorized_capital: company?.authorized_capital?.toString() ?? "",
    paid_up_capital: company?.paid_up_capital?.toString() ?? "",
    share_value: company?.share_value?.toString() ?? "",
    total_shares: company?.total_shares?.toString() ?? "",
    fiscal_year_start: company?.fiscal_year_start ?? "",
    fiscal_year_end: company?.fiscal_year_end ?? "",
    sector: company?.sector ?? "",
    phone: company?.phone ?? "",
    email: company?.email ?? "",
    website: company?.website ?? "",
    bank_name: company?.bank_name ?? "",
    bank_account_number: company?.bank_account_number ?? "",
    bank_branch: company?.bank_branch ?? "",
    auditor_name: company?.auditor_name ?? "",
    auditor_firm: company?.auditor_firm ?? "",
    auditor_ican_number: company?.auditor_ican_number ?? "",
  });

  function set(key: string, value: string) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  // Auto-transliterate English name to Nepali with debounce
  const transliterate = useCallback((text: string) => {
    if (transliterateTimer.current) clearTimeout(transliterateTimer.current);
    if (!text.trim()) {
      set("name_ne", "");
      return;
    }
    transliterateTimer.current = setTimeout(async () => {
      setTransliterating(true);
      try {
        const result = await transliterateToNepali(text);
        // Only set if user hasn't manually edited the Nepali field
        setForm((prev) => {
          // If Nepali name was auto-generated or empty, update it
          if (!prev.name_ne || prev._nameNeAutoGenerated === "true") {
            return { ...prev, name_ne: result, _nameNeAutoGenerated: "true" };
          }
          return prev;
        });
      } catch {
        // Silently fail — user can type manually
      } finally {
        setTransliterating(false);
      }
    }, 600);
  }, []);

  // Track manual edits to Nepali name
  function setNameNe(value: string) {
    setForm((prev) => ({ ...prev, name_ne: value, _nameNeAutoGenerated: "false" }));
  }

  // Trigger transliteration when English name changes
  useEffect(() => {
    if (form.name_en && !company) {
      transliterate(form.name_en);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form.name_en]);

  // Province change resets district and municipality
  function handleProvinceChange(province: string | null) {
    if (!province) return;
    setSelectedProvince(province);
    set("district_en", "");
    set("district_ne", "");
    set("municipality_en", "");
    set("municipality_ne", "");
  }

  // District change auto-fills Nepali and resets municipality
  function handleDistrictChange(districtEn: string | null) {
    if (!districtEn) return;
    const districtNe = findDistrictNepali(districtEn);
    setForm((prev) => ({
      ...prev,
      district_en: districtEn,
      district_ne: districtNe ?? "",
      municipality_en: "",
      municipality_ne: "",
    }));
  }

  // Municipality change auto-fills Nepali
  function handleMunicipalityChange(municipalityEn: string | null) {
    if (!municipalityEn) return;
    const municipalityNe = findMunicipalityNepali(municipalityEn);
    setForm((prev) => ({
      ...prev,
      municipality_en: municipalityEn,
      municipality_ne: municipalityNe ?? "",
    }));
  }

  const districts = selectedProvince ? getDistricts(selectedProvince) : [];
  const municipalities = form.district_en
    ? getMunicipalities(form.district_en)
    : [];

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSubmitting(true);
    setErrors({});

    const payload: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(form)) {
      if (key.startsWith("_")) continue; // Skip internal tracking fields
      if (value !== "") {
        if (
          [
            "authorized_capital",
            "paid_up_capital",
            "share_value",
            "total_shares",
          ].includes(key)
        ) {
          payload[key] = parseInt(value, 10) || 0;
        } else {
          payload[key] = value;
        }
      }
    }

    try {
      if (company) {
        await api.put<Company>(`/companies/${company.uuid}`, payload);
        router.push(`/companies/${company.uuid}`);
      } else {
        const res = await api.post<Company>("/companies", payload);
        router.push(`/companies/${res.data.uuid}`);
      }
    } catch (err) {
      if (err instanceof ApiError && err.body.errors) {
        setErrors(err.body.errors as Record<string, string[]>);
      } else {
        setErrors({
          _general: ["Something went wrong. Please try again."],
        });
      }
    } finally {
      setSubmitting(false);
    }
  }

  function fieldError(key: string) {
    return errors[key] ? (
      <p className="text-xs text-destructive mt-1">{errors[key]?.join(", ")}</p>
    ) : null;
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-8">
      {errors._general && (
        <div className="rounded-xl bg-destructive/10 border border-destructive/20 px-4 py-3 text-sm text-destructive">
          {errors._general.join(", ")}
        </div>
      )}

      {/* Company Identity */}
      <section className="rounded-xl border bg-card shadow-sm overflow-hidden">
        <div className="border-b bg-muted/30 px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <Building2Icon className="size-5" />
            </div>
            <div>
              <h3 className="font-semibold text-base">Company Identity</h3>
              <p className="text-xs text-muted-foreground">
                Basic registration details as per OCR certificate
              </p>
            </div>
          </div>
        </div>
        <div className="p-6 space-y-5">
          {/* Company Name */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">
                Company Name (English) <span className="text-destructive">*</span>
              </Label>
              <Input
                value={form.name_en}
                onChange={(e) => set("name_en", e.target.value)}
                placeholder="e.g. Saral Hisab Pvt. Ltd."
                aria-invalid={!!errors.name_en}
                className="h-10"
              />
              {fieldError("name_en")}
            </div>
            <div className="space-y-1.5">
              <div className="flex items-center gap-2">
                <Label className="text-sm font-medium">Company Name (Nepali)</Label>
                {transliterating && (
                  <span className="inline-flex items-center gap-1 text-xs text-muted-foreground">
                    <Loader2Icon className="size-3 animate-spin" />
                    Transliterating...
                  </span>
                )}
                {!transliterating && form.name_ne && form._nameNeAutoGenerated === "true" && (
                  <span className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-medium text-primary">
                    <SparklesIcon className="size-2.5" />
                    Auto-generated
                  </span>
                )}
              </div>
              <NepaliInput
                value={form.name_ne ?? ""}
                onChange={setNameNe}
                placeholder="कम्पनीको नाम"
                className="h-10 flex w-full rounded-lg border border-input bg-transparent px-3 py-1 text-sm shadow-xs placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50"
              />
              <p className="text-[11px] text-muted-foreground">
                Auto-filled from English name. Edit to override.
              </p>
              {fieldError("name_ne")}
            </div>
          </div>

          {/* Type + Reg Number + Date */}
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">
                Company Type <span className="text-destructive">*</span>
              </Label>
              <Select
                value={form.company_type}
                onValueChange={(val) => {
                  if (val) set("company_type", val);
                }}
              >
                <SelectTrigger className="w-full h-10">
                  <SelectValue>
                    {COMPANY_TYPE_LABELS[form.company_type as CompanyType] ?? form.company_type}
                  </SelectValue>
                </SelectTrigger>
                <SelectContent>
                  {COMPANY_TYPES.map(([value, label]) => (
                    <SelectItem key={value} value={value}>
                      {label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {fieldError("company_type")}
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Registration Number</Label>
              <Input
                value={form.registration_number ?? ""}
                onChange={(e) => set("registration_number", e.target.value)}
                placeholder="e.g. 123456/078/079"
                className="h-10"
              />
              {fieldError("registration_number")}
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Incorporation Date</Label>
              <Input
                type="date"
                value={form.incorporation_date ?? ""}
                onChange={(e) => set("incorporation_date", e.target.value)}
                className="h-10"
              />
              {fieldError("incorporation_date")}
            </div>
          </div>

          {/* PAN + VAT */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">PAN Number</Label>
              <Input
                value={form.pan_number ?? ""}
                onChange={(e) => set("pan_number", e.target.value)}
                placeholder="9 digit PAN number"
                className="h-10"
              />
              {fieldError("pan_number")}
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">VAT Number</Label>
              <Input
                value={form.vat_number ?? ""}
                onChange={(e) => set("vat_number", e.target.value)}
                placeholder="Optional — only if VAT registered"
                className="h-10"
              />
              {fieldError("vat_number")}
            </div>
          </div>
        </div>
      </section>

      {/* Registered Address */}
      <section className="rounded-xl border bg-card shadow-sm overflow-hidden">
        <div className="border-b bg-muted/30 px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="flex size-9 items-center justify-center rounded-lg bg-emerald-500/10 text-emerald-600">
              <MapPinIcon className="size-5" />
            </div>
            <div>
              <h3 className="font-semibold text-base">Registered Address</h3>
              <p className="text-xs text-muted-foreground">
                Office address as registered with OCR. Nepali names auto-fill when you select.
              </p>
            </div>
          </div>
        </div>
        <div className="p-6 space-y-5">
          {/* Province + District + Municipality cascading */}
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Province</Label>
              <Select
                value={selectedProvince}
                onValueChange={handleProvinceChange}
              >
                <SelectTrigger className="w-full h-10">
                  <SelectValue placeholder="Select province" />
                </SelectTrigger>
                <SelectContent>
                  {NEPAL_PROVINCES.map((p) => (
                    <SelectItem key={p.name_en} value={p.name_en}>
                      {p.name_en}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">District</Label>
              <Select
                value={form.district_en}
                onValueChange={handleDistrictChange}
                disabled={!selectedProvince}
              >
                <SelectTrigger className="w-full h-10">
                  <SelectValue
                    placeholder={
                      selectedProvince
                        ? "Select district"
                        : "Select province first"
                    }
                  />
                </SelectTrigger>
                <SelectContent>
                  {districts.map((d) => (
                    <SelectItem key={d.name_en} value={d.name_en}>
                      {d.name_en} ({d.name_ne})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {fieldError("district_en")}
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Municipality / Rural Municipality</Label>
              <Select
                value={form.municipality_en}
                onValueChange={handleMunicipalityChange}
                disabled={!form.district_en}
              >
                <SelectTrigger className="w-full h-10">
                  <SelectValue
                    placeholder={
                      form.district_en
                        ? "Select municipality"
                        : "Select district first"
                    }
                  />
                </SelectTrigger>
                <SelectContent>
                  {municipalities.map((m) => (
                    <SelectItem key={m.name_en} value={m.name_en}>
                      {m.name_en}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {fieldError("municipality_en")}
            </div>
          </div>

          {/* Auto-filled Nepali names (read-only visual) */}
          {(form.district_ne || form.municipality_ne) && (
            <div className="rounded-lg bg-muted/50 border border-muted px-4 py-3">
              <p className="text-xs text-muted-foreground mb-1.5 flex items-center gap-1">
                <SparklesIcon className="size-3" />
                Auto-filled Nepali
              </p>
              <div className="grid gap-2 sm:grid-cols-2 text-sm">
                {form.district_ne && (
                  <div>
                    <span className="text-muted-foreground">District: </span>
                    <span className="font-medium">{form.district_ne}</span>
                  </div>
                )}
                {form.municipality_ne && (
                  <div>
                    <span className="text-muted-foreground">Municipality: </span>
                    <span className="font-medium">{form.municipality_ne}</span>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Ward + Tole */}
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Ward No.</Label>
              <Input
                value={form.ward ?? ""}
                onChange={(e) => set("ward", e.target.value)}
                placeholder="e.g. 10"
                className="h-10"
                type="number"
                min="1"
                max="35"
              />
              {fieldError("ward")}
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Tole (English)</Label>
              <Input
                value={form.tole_en ?? ""}
                onChange={(e) => set("tole_en", e.target.value)}
                placeholder="e.g. New Baneshwor"
                className="h-10"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Tole (Nepali)</Label>
              <NepaliInput
                value={form.tole_ne ?? ""}
                onChange={(val) => set("tole_ne", val)}
                placeholder="e.g. नयाँ बानेश्वर"
                className="h-10 flex w-full rounded-lg border border-input bg-transparent px-3 py-1 text-sm shadow-xs placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Capital Structure */}
      <section className="rounded-xl border bg-card shadow-sm overflow-hidden">
        <div className="border-b bg-muted/30 px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="flex size-9 items-center justify-center rounded-lg bg-amber-500/10 text-amber-600">
              <LandmarkIcon className="size-5" />
            </div>
            <div>
              <h3 className="font-semibold text-base">Capital Structure</h3>
              <p className="text-xs text-muted-foreground">
                Share capital details from Memorandum of Association
              </p>
            </div>
          </div>
        </div>
        <div className="p-6 space-y-5">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Authorized Capital (NPR)</Label>
              <Input
                type="number"
                value={form.authorized_capital ?? ""}
                onChange={(e) => set("authorized_capital", e.target.value)}
                placeholder="e.g. 10,00,000"
                className="h-10"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Paid-up Capital (NPR)</Label>
              <Input
                type="number"
                value={form.paid_up_capital ?? ""}
                onChange={(e) => set("paid_up_capital", e.target.value)}
                placeholder="e.g. 10,00,000"
                className="h-10"
              />
            </div>
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Share Value (NPR per share)</Label>
              <Input
                type="number"
                value={form.share_value ?? ""}
                onChange={(e) => set("share_value", e.target.value)}
                placeholder="e.g. 100"
                className="h-10"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Total Shares</Label>
              <Input
                type="number"
                value={form.total_shares ?? ""}
                onChange={(e) => set("total_shares", e.target.value)}
                placeholder="e.g. 10,000"
                className="h-10"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Contact & Banking */}
      <section className="rounded-xl border bg-card shadow-sm overflow-hidden">
        <div className="border-b bg-muted/30 px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="flex size-9 items-center justify-center rounded-lg bg-blue-500/10 text-blue-600">
              <PhoneIcon className="size-5" />
            </div>
            <div>
              <h3 className="font-semibold text-base">Contact & Banking</h3>
              <p className="text-xs text-muted-foreground">
                Company contact details and primary bank account
              </p>
            </div>
          </div>
        </div>
        <div className="p-6 space-y-5">
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Phone</Label>
              <Input
                value={form.phone ?? ""}
                onChange={(e) => set("phone", e.target.value)}
                placeholder="e.g. 01-5555555"
                className="h-10"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Email</Label>
              <Input
                type="email"
                value={form.email ?? ""}
                onChange={(e) => set("email", e.target.value)}
                placeholder="e.g. info@company.com.np"
                className="h-10"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Sector</Label>
              <Input
                value={form.sector ?? ""}
                onChange={(e) => set("sector", e.target.value)}
                placeholder="e.g. IT, Trading, Manufacturing"
                className="h-10"
              />
            </div>
          </div>
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Bank Name</Label>
              <Input
                value={form.bank_name ?? ""}
                onChange={(e) => set("bank_name", e.target.value)}
                placeholder="e.g. Nepal Bank Ltd."
                className="h-10"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Account Number</Label>
              <Input
                value={form.bank_account_number ?? ""}
                onChange={(e) => set("bank_account_number", e.target.value)}
                placeholder="Bank account number"
                className="h-10"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Branch</Label>
              <Input
                value={form.bank_branch ?? ""}
                onChange={(e) => set("bank_branch", e.target.value)}
                placeholder="e.g. New Road Branch"
                className="h-10"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Auditor */}
      <section className="rounded-xl border bg-card shadow-sm overflow-hidden">
        <div className="border-b bg-muted/30 px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="flex size-9 items-center justify-center rounded-lg bg-violet-500/10 text-violet-600">
              <ShieldCheckIcon className="size-5" />
            </div>
            <div>
              <h3 className="font-semibold text-base">Auditor Details</h3>
              <p className="text-xs text-muted-foreground">
                Required for annual compliance and financial documents
              </p>
            </div>
          </div>
        </div>
        <div className="p-6">
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Auditor Name</Label>
              <Input
                value={form.auditor_name ?? ""}
                onChange={(e) => set("auditor_name", e.target.value)}
                placeholder="Full name"
                className="h-10"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">Audit Firm</Label>
              <Input
                value={form.auditor_firm ?? ""}
                onChange={(e) => set("auditor_firm", e.target.value)}
                placeholder="Firm name"
                className="h-10"
              />
            </div>
            <div className="space-y-1.5">
              <Label className="text-sm font-medium">ICAN Number</Label>
              <Input
                value={form.auditor_ican_number ?? ""}
                onChange={(e) => set("auditor_ican_number", e.target.value)}
                placeholder="ICAN membership number"
                className="h-10"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Submit */}
      <div className="flex justify-end gap-3 pt-2">
        <Button
          type="button"
          variant="outline"
          size="lg"
          onClick={() => router.back()}
          className="min-w-[120px]"
        >
          Cancel
        </Button>
        <Button
          type="submit"
          size="lg"
          disabled={submitting}
          className="min-w-[160px]"
        >
          {submitting && <Loader2Icon className="mr-2 size-4 animate-spin" />}
          {company ? "Update Company" : "Save Company"}
        </Button>
      </div>
    </form>
  );
}
